force-app/main/default/objects/Case/fields/NumeroColeta__c.field-meta.xml
<CustomField>
    <fullName>NumeroColeta__c</fullName>
    <label>Número do E-Ticket</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/ObjetoPostagemReversa__c.object-meta.xml
<CustomObject>
    <description>Objeto criado para armazenar os objetos de Postagem Reversa criados para os casos de Postagem Reversa</description>
    <label>Objeto Postagem Reversa</label>
    <nameField>
        <displayFormat>OPS-{0000}</displayFormat>
        <label>Nome de Objeto Postagem Reversa</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objetos Postagem Reversa</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Objetos Postagem Reversa</relationshipLabel>
    <relationshipName>ObjetosPostagemReversa</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/idObjetoColeta__c.field-meta.xml
<CustomField>
    <fullName>idObjetoColeta__c</fullName>
    <label>idObjetoColeta__c</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/NumeroEtiqueta__c.field-meta.xml
<CustomField>
    <fullName>NumeroEtiqueta__c</fullName>
    <label>Número de Rastreamento</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PosPostagemControllerTest.cls
@isTest
public with sharing class PosPostagemControllerTest {
    
    @isTest
    public static void controllerTest(){

        Account contaTeste = new Account();
        contaTeste.Name    = 'Conta Teste';
        insert contaTeste;

        Case casoTeste              = new Case();
        casoTeste.AccountId         = contaTeste.Id;
        casoTeste.Status            = 'New';
        casoTeste.Origin            = 'Commercial';
        casoTeste.Priority          = 'Medium';
        casoTeste.NumeroColeta__c   = '108518672';
        insert casoTeste;

        Account contaTesteERRO      = new Account();
        contaTesteERRO.Name         = 'Conta Teste';
        insert contaTesteERRO;

        Case casoTesteERRO                  = new Case();
        casoTesteERRO.AccountId             = contaTesteERRO.Id;
        casoTesteERRO.Status                = 'New';
        casoTesteERRO.Origin                = 'Commercial';
        casoTesteERRO.Priority              = 'Medium';
        casoTesteERRO.NumeroColeta__c       = '108518672';
        insert casoTesteERRO;

        ObjetoPostagemReversa__c objetoPostagemReversaTeste = new ObjetoPostagemReversa__c();
        objetoPostagemReversaTeste.Caso__c                  = casoTeste.Id;
        objetoPostagemReversaTeste.idObjetoColeta__c        = '553379';
        objetoPostagemReversaTeste.NumeroEtiqueta__c        = 'QB201737764BR';
        insert objetoPostagemReversaTeste;

        Test.setMock(HttpCalloutMock.class, new RastreioCalloutMock());
        Test.startTest();
        PosPostagemController.PosPostagemController(casoTeste.Id);
        PosPostagemController.PosPostagemController('0');
        PosPostagemController.PosPostagemController(casoTesteERRO.Id);
        Test.stopTest();
    }
}