force-app/main/default/objects/Case/fields/NumeroColeta__c.field-meta.xml
<CustomField>
    <fullName>NumeroColeta__c</fullName>
    <label>Número do E-Ticket</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ReversaStatus__c.field-meta.xml
<CustomField>
    <fullName>ReversaStatus__c</fullName>
    <description>Rastreia o processo de Reversa dos Correios através dos Status.</description>
    <label>Status da Reversa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando Objeto na Agência</fullName>
                <label>Aguardando Postagem Consumidor</label>
            </value>
            <value>
                <fullName>Prazo de Utilização Expirado</fullName>
                <label>Prazo de Postagem Expirado</label>
            </value>
            <value>
                <fullName>Coletado</fullName>
                <label>Em rota para o CD</label>
            </value>
            <value>
                <fullName>Entrega não realizada</fullName>
            </value>
            <value>
                <fullName>Aguardando Check-in Reversa</fullName>
            </value>
            <value>
                <fullName>Reversa Liberada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/ObjetoPostagemReversa__c.object-meta.xml
<CustomObject>
    <description>Objeto criado para armazenar os objetos de Postagem Reversa criados para os casos de Postagem Reversa</description>
    <label>Objeto Postagem Reversa</label>
    <nameField>
        <displayFormat>OPS-{0000}</displayFormat>
        <label>Nome de Objeto Postagem Reversa</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objetos Postagem Reversa</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Objetos Postagem Reversa</relationshipLabel>
    <relationshipName>ObjetosPostagemReversa</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/DataUltimaAtualizacao__c.field-meta.xml
<CustomField>
    <fullName>DataUltimaAtualizacao__c</fullName>
    <label>Data da Última Atualização</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/EnvioConcluido__c.field-meta.xml
<CustomField>
    <fullName>EnvioConcluido__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Campo para informar se, baseado no status do rastreamento dos Correios, o envio do objeto já foi concluído.</inlineHelpText>
    <label>Envio Concluído?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/HoraUltimaAtualizacao__c.field-meta.xml
<CustomField>
    <fullName>HoraUltimaAtualizacao__c</fullName>
    <label>Hora da Última Atualização</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/idObjetoColeta__c.field-meta.xml
<CustomField>
    <fullName>idObjetoColeta__c</fullName>
    <label>idObjetoColeta__c</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/NumeroEtiqueta__c.field-meta.xml
<CustomField>
    <fullName>NumeroEtiqueta__c</fullName>
    <label>Número de Rastreamento</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/UltimoStatusRastreamento__c.field-meta.xml
<CustomField>
    <fullName>UltimoStatusRastreamento__c</fullName>
    <label>Último Status de Rastreamento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CorreiosRastreamentoBatch.cls
public with sharing class CorreiosRastreamentoBatch implements Database.Batchable<sObject>, Database.AllowsCallouts {

	public Database.QueryLocator start(Database.BatchableContext bc) {

		List<String> caseStatusToFilter = new List<String>{'Em atendimento', 'Reaberto'};

        String query = 'SELECT id, caso__c, idObjetoColeta__c, NumeroEtiqueta__c, UltimoStatusRastreamento__c, DataUltimaAtualizacao__c, ReversaStatus__c FROM ObjetoPostagemReversa__c WHERE NumeroEtiqueta__c != null AND EnvioConcluido__c = false AND caso__r.status IN: caseStatusToFilter AND caso__r.NumeroColeta__c != null AND ReversaStatus__c = \'Coletado\'';
		return Database.getQueryLocator(query);

	}

	// batch runs in single scope because correios integration only work with one ticket number at a time
	public void execute(Database.BatchableContext bc, List<ObjetoPostagemReversa__c> scope) {

		Map<String, ObjetoPostagemReversa__c> numeroEtiquetaToObjetoPostagemReversa = new Map<String, ObjetoPostagemReversa__c>();

        Set<Id> caseIds = new Set<Id>();

        for(ObjetoPostagemReversa__c objPostagemReversa : scope) {
            numeroEtiquetaToObjetoPostagemReversa.put(objPostagemReversa.NumeroEtiqueta__c, objPostagemReversa);
            caseIds.add(objPostagemReversa.caso__c);
        }

        SroXML2 response = RastreioCallout.getStatusRastreamento(new List<String>(numeroEtiquetaToObjetoPostagemReversa.keySet()));

        for(SROXML2.ObjetoRastreio objeto : response.objeto) {
            SroXML2.Evento ultimoEvento = objeto.evento[0];
            numeroEtiquetaToObjetoPostagemReversa.get(objeto.numero).UltimoStatusRastreamento__c = ultimoEvento.descricao;
            numeroEtiquetaToObjetoPostagemReversa.get(objeto.numero).DataUltimaAtualizacao__c    = ultimoEvento.data;
            numeroEtiquetaToObjetoPostagemReversa.get(objeto.numero).HoraUltimaAtualizacao__c    = ultimoEvento.hora;
            //alterar para verificar os códigos de status concluídos a partir do metadado
            if(true) { // ultimoEvento.tipo == 'BDE' && listaDeCodigosConcluidos.contains(ultimoEvento.status)?
                numeroEtiquetaToObjetoPostagemReversa.get(objeto.numero).EnvioConcluido__c = true;
            }
        }

        update numeroEtiquetaToObjetoPostagemReversa.values();
	}

	public void finish(Database.BatchableContext bc) {
		
	}
}