force-app/main/default/objects/Case/fields/NumeroColeta__c.field-meta.xml
<CustomField>
    <fullName>NumeroColeta__c</fullName>
    <label>Número do E-Ticket</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/ObjetoPostagemReversa__c.object-meta.xml
<CustomObject>
    <description>Objeto criado para armazenar os objetos de Postagem Reversa criados para os casos de Postagem Reversa</description>
    <label>Objeto Postagem Reversa</label>
    <nameField>
        <displayFormat>OPS-{0000}</displayFormat>
        <label>Nome de Objeto Postagem Reversa</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objetos Postagem Reversa</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Objetos Postagem Reversa</relationshipLabel>
    <relationshipName>ObjetosPostagemReversa</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/idObjetoColeta__c.field-meta.xml
<CustomField>
    <fullName>idObjetoColeta__c</fullName>
    <label>idObjetoColeta__c</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SolicitarCodigoRastreioControllerTest.cls
@isTest
public with sharing class SolicitarCodigoRastreioControllerTest {
    
    @isTest
    public static void solicitaCodigoRastreioTest() {
        Account contaTeste = new Account();
        contaTeste.Name    = 'Conta Teste';
        insert contaTeste;

        Case casoTeste              = new Case();
        casoTeste.AccountId         = contaTeste.Id;
        casoTeste.Status            = 'New';
        casoTeste.Origin            = 'Commercial';
        casoTeste.Priority          = 'Medium';
        casoTeste.NumeroColeta__c   = '108518672';
        insert casoTeste;

        Account contaTeste2 = new Account();
        contaTeste2.Name    = 'Conta Teste';
        insert contaTeste2;

        Case casoTeste2              = new Case();
        casoTeste2.AccountId         = contaTeste.Id;
        casoTeste2.Status            = 'New';
        casoTeste2.Origin            = 'Commercial';
        casoTeste2.Priority          = 'Medium';
        casoTeste2.NumeroColeta__c   = '108518672';
        insert casoTeste2;

        ObjetoPostagemReversa__c objetoPostagemReversaTeste = new ObjetoPostagemReversa__c();
        objetoPostagemReversaTeste.Caso__c                  = casoTeste.Id;
        objetoPostagemReversaTeste.idObjetoColeta__c        = '553379';
        insert objetoPostagemReversaTeste;

        Test.setMock(WebServiceMock.class, new SolicitarCodigoRastreioMock());
        Test.startTest();
        SolicitarCodigoRastreioController.recordIdCaso(casoTeste.Id);
        SolicitarCodigoRastreioController.recordIdCaso(casoTeste2.Id);
        SolicitarCodigoRastreioController.solicitaCodigoRastreio(casoTeste.Id);
        SolicitarCodigoRastreioController.solicitaCodigoRastreio(casoTeste2.Id);
        Test.stopTest();
    }
}