force-app/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena as Marcas cadastradas no processo da Infracommerce.</description>
    <label>Marca</label>
    <nameField>
        <label>Nome da Marca</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marcas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>Determina se o registro está ativo ou não.</description>
    <label>Ativo ?</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Ativo</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <label>Inativo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Brand__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Tipo do cadastro da Marca.</description>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipos_de_Marcas</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Customer_Document__c.field-meta.xml
<CustomField>
    <fullName>Customer_Document__c</fullName>
    <label>Documento do Cliente</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Customer_Email__c</fullName>
    <label>Email do Cliente</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Customer_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Last_Name__c</fullName>
    <label>Sobrenome do Cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <label>Nome do Cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Customer_Phone__c.field-meta.xml
<CustomField>
    <fullName>Customer_Phone__c</fullName>
    <label>Telefone do Cliente</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/Destination_Name__c.field-meta.xml
<CustomField>
    <fullName>Destination_Name__c</fullName>
    <label>Nome do Destino</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Destination_return_to_seller__c.field-meta.xml
<CustomField>
    <fullName>Destination_return_to_seller__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retornou para loja</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Destination_seller_id__c.field-meta.xml
<CustomField>
    <fullName>Destination_seller_id__c</fullName>
    <label>Id Loja</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Destination_seller_info__c.field-meta.xml
<CustomField>
    <fullName>Destination_seller_info__c</fullName>
    <label>Informação da Loja</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Destination_Type__c.field-meta.xml
<CustomField>
    <fullName>Destination_Type__c</fullName>
    <label>Tipo de Destino</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Ecommerce_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Ecommerce_Order_Id__c</fullName>
    <label>Id do Pedido Ecommerce</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Event_Name__c</fullName>
    <label>Event Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Id_Reverse__c.field-meta.xml
<CustomField>
    <fullName>Id_Reverse__c</fullName>
    <label>Id Reversa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Nota Fiscal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Marca relacionada ao caso.</description>
    <label>Marca</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>MarcaCasos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Order_Id__c</fullName>
    <label>Id do Pedido</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Reverse_Type__c.field-meta.xml
<CustomField>
    <fullName>Reverse_Type__c</fullName>
    <label>Tipo de Reversa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Signature__c.field-meta.xml
<CustomField>
    <fullName>Signature__c</fullName>
    <label>Assinatura</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/status_id__c.field-meta.xml
<CustomField>
    <fullName>status_id__c</fullName>
    <label>Id do Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Valor Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/Tracking_Authorization_Code__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Authorization_Code__c</fullName>
    <label>Código de Autorização de Rastreio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Tracking_Code__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Code__c</fullName>
    <label>Código de Rastreio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Tracking_Ecommerce_Order__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Ecommerce_Order__c</fullName>
    <label>Número Pedido Ecommerce</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Tracking_Expire_Date__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Expire_Date__c</fullName>
    <label>Data de Expiração Rastreio</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Tracking_Status__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Status__c</fullName>
    <label>Status do Rastreio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Troque_Facil.recordType-meta.xml
<RecordType>
    <fullName>Troque_Facil</fullName>
    <active>true</active>
    <businessProcess>Caso de Troca</businessProcess>
    <label>Troque Fácil</label>
</RecordType>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazenará as NFs populadas pela integração.</description>
    <label>Nota Fiscal</label>
    <nameField>
        <label>Nota Fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas Fiscais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marca</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Notas Fiscais</relationshipLabel>
    <relationshipName>Notas_Fiscais</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>invoice type NFe or CFe</description>
    <label>Tipo de Nota</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NFe</fullName>
            </value>
            <value>
                <fullName>CFe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/ObjetoPostagemReversa__c.object-meta.xml
<CustomObject>
    <description>Objeto criado para armazenar os objetos de Postagem Reversa criados para os casos de Postagem Reversa</description>
    <label>Objeto Postagem Reversa</label>
    <nameField>
        <displayFormat>OPS-{0000}</displayFormat>
        <label>Nome de Objeto Postagem Reversa</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objetos Postagem Reversa</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Objetos Postagem Reversa</relationshipLabel>
    <relationshipName>ObjetosPostagemReversa</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/idObjetoColeta__c.field-meta.xml
<CustomField>
    <fullName>idObjetoColeta__c</fullName>
    <label>idObjetoColeta__c</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/Ord_Product_Reverse__c.field-meta.xml
<CustomField>
    <fullName>Ord_Product_Reverse__c</fullName>
    <label>Pedido do Produto da Reversa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/Product_Comments_Reverse__c.field-meta.xml
<CustomField>
    <fullName>Product_Comments_Reverse__c</fullName>
    <label>Comentário do Produto Reversa</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/Product_Name_Reverse__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_Reverse__c</fullName>
    <label>Nome do Produto Reversa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/Product_Order_Id_Reverse__c.field-meta.xml
<CustomField>
    <fullName>Product_Order_Id_Reverse__c</fullName>
    <label>Id do Pedido Produto Reversa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/Product_Price_Reverse__c.field-meta.xml
<CustomField>
    <fullName>Product_Price_Reverse__c</fullName>
    <label>Preço do Produto Reversa</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/Product_Protocol_Reverse__c.field-meta.xml
<CustomField>
    <fullName>Product_Protocol_Reverse__c</fullName>
    <label>Protocolo Produto Reversa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/Product_Reason_Action_Reverse__c.field-meta.xml
<CustomField>
    <fullName>Product_Reason_Action_Reverse__c</fullName>
    <label>Ação do Produto do Motivo Reversa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/Product_Reason_Description_Reverse__c.field-meta.xml
<CustomField>
    <fullName>Product_Reason_Description_Reverse__c</fullName>
    <label>Descrição do Produto do Motivo Reversa</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/Product_Reverse_Action__c.field-meta.xml
<CustomField>
    <fullName>Product_Reverse_Action__c</fullName>
    <label>Ação do Produto Reversa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/Product_Selling_Price_Reverse__c.field-meta.xml
<CustomField>
    <fullName>Product_Selling_Price_Reverse__c</fullName>
    <label>Preço de Venda Produto Reversa</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/Product_Situation_Reverse__c.field-meta.xml
<CustomField>
    <fullName>Product_Situation_Reverse__c</fullName>
    <label>Situação Produto Reversa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/Product_SKU_Reverse__c.field-meta.xml
<CustomField>
    <fullName>Product_SKU_Reverse__c</fullName>
    <label>SKU Produto Reversa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/Qty_Product_Reverse__c.field-meta.xml
<CustomField>
    <fullName>Qty_Product_Reverse__c</fullName>
    <label>Quantidade do Produto da Reversa</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/Received_Qty_Product_Reverse__c.field-meta.xml
<CustomField>
    <fullName>Received_Qty_Product_Reverse__c</fullName>
    <label>Quantidade Recebida Produto Reversa</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/Requested_Qty_Produtct_Reverse__c.field-meta.xml
<CustomField>
    <fullName>Requested_Qty_Produtct_Reverse__c</fullName>
    <label>Quantidade Solicitada do Produto Reversa</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/recordTypes/Troque_Facil.recordType-meta.xml
<RecordType>
    <fullName>Troque_Facil</fullName>
    <active>true</active>
    <label>Troque Fácil</label>
</RecordType>

force-app/main/default/classes/IntegrationTroqueFacilIN.cls
@RestResource(urlMapping='/troque-facil-in')
global with sharing class IntegrationTroqueFacilIN {
    @HttpPost
    global static void upsertCase() {

        Boolean hasError = false;

        List<TemplateDataIntegrationFields.Response> responseList = new List<TemplateDataIntegrationFields.Response>();

        Brand__c nikeBrand = [SELECT Id FROM Brand__c WHERE ExternalId__c = 'NIKE' AND Active__c = 'Active' LIMIT 1];

        try {

            System.debug('RestContext.request.requestBody => ' + RestContext.request.requestBody);

            String body = RestContext.request.requestBody.toString();

            Type requestType = Type.forName('IntegrationTroqueFacilIN.TroqueFacilIN');
            TroqueFacilIN request = (TroqueFacilIN) JSON.deserialize(RestContext.request.requestBody.toString(), requestType);

            Id reverseObjectTroqueFacilRTId = Schema.SObjectType.ObjetoPostagemReversa__c.getRecordTypeInfosByDeveloperName().get('Troque_Facil').getRecordTypeId();

            if(request != null && request.data != null) {

                Case newCase = new Case();
                
                newCase.Subject                     = 'Troque Fácil - ' + request.data?.reverse?.id;
                newCase.Marca__c                    = nikeBrand.Id;
                newCase.RecordTypeId                = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Troque_Facil').getRecordTypeId();
                newCase.Signature__c                = request.signature;
                newCase.Tracking_Ecommerce_Order__c = request.data?.ecommerce_order;
                newCase.Event_Name__c               = request.event_name;
                
                newCase.Customer_Name__c      = request.data?.customer?.first_name;
                newCase.Customer_Last_Name__c = request.data?.customer?.last_name;
                newCase.Customer_Email__c     = request.data?.customer?.email;
                newCase.Customer_Document__c  = request.data?.customer?.document.replaceAll('[^0-9]+', '');
                newCase.Customer_Phone__c     = request.data?.customer?.phone;

                newCase.Id_Reverse__c         = String.valueOf(request.data?.reverse?.id);
                // newCase.Reverse_Type__c       = request.data?.reverse?.reverse_type;
                newCase.Reverse_Type__c       = request.data?.reverse?.reverse_type_name;
                newCase.Ecommerce_Order_Id__c = String.valueOf(request.data?.reverse?.ecommerce_order_id);
                newCase.Total_Amount__c       = Decimal.valueOf(request.data?.reverse?.total_amount);
                newCase.Origin__c             = request.data?.reverse?.origin;
                newCase.Status_Id__c          = String.valueOf(request.data?.reverse?.status_id);
                newCase.Type__c               = request.data?.reverse?.type;
                newCase.Invoice__c            = request.data?.ecommerce_order;

                if(request.data?.reverse?.destination_data != null) {
                    newCase.Tracking_Expire_Date__c        = Datetime.valueOf(request.data?.reverse?.tracking?.expire_date);
                    // newCase.Tracking_Status__c             = request.data?.reverse?.tracking?.status;
                    // newCase.Tracking_Message__c            = request.data?.reverse?.tracking?.message;
                    newCase.Tracking_Authorization_Code__c = request.data?.reverse?.tracking?.authorization_code; // verificar se o código pode começar com 0
                    // newCase.Tracking_Code__c               = request.data?.reverse?.tracking?.tracking_code;
                }

                if(request.data?.reverse?.destination_data != null) {
                    newCase.Destination_Name__c             = request.data?.reverse?.destination_data.name;
                    newCase.Destination_Type__c             = request.data?.reverse?.destination_data.type;
                    newCase.Destination_Seller_info__c      = request.data?.reverse?.destination_data.seller_info;
                    newCase.Destination_Seller_id__c        = request.data?.reverse?.destination_data.seller_id;
                    newCase.Destination_Return_to_seller__c = request.data?.reverse?.destination_data.return_to_seller;
                }

                List<ObjetoPostagemReversa__c> postalObjectsToInsert = new List<ObjetoPostagemReversa__c>();
                String fullDescriptionCase = '';

                if(request.data?.reverse?.products != null && !request.data?.reverse?.products.isEmpty()) {
                
                    // iteração dos produtos (alterar para Objeto Postagem Reversa)
                
                    for(Product product : request.data?.reverse?.products) {

                        ObjetoPostagemReversa__c newPostalObject = new ObjetoPostagemReversa__c();

                        newPostalObject.Product_Order_Id_Reverse__c       = String.valueOf(product.order_id);
                        newPostalObject.Product_Price_Reverse__c          = Decimal.valueOf(product.price);
                        newPostalObject.Product_Selling_Price_Reverse__c  = Decimal.valueOf(product.selling_price);
                        newPostalObject.Product_SKU_Reverse__c            = product.sku;
                        newPostalObject.Product_Name_Reverse__c           = product.name;
                        newPostalObject.Product_Protocol_Reverse__c       = product.protocol;
                        newPostalObject.Product_Reverse_Action__c         = product.reverse_action;
                        // newPostalObject.Product_Reverse_Id__c             = String.valueOf(product.reverse_id);
                        newPostalObject.Product_Comments_Reverse__c       = product.comments;
                        newPostalObject.Ord_Product_Reverse__c            = request.data?.ecommerce_order;
                        newPostalObject.Qty_Product_Reverse__c            = product.qty;
                        newPostalObject.Requested_Qty_Produtct_Reverse__c = product.requested_qty;
                        newPostalObject.Received_Qty_Product_Reverse__c   = product.received_qty;
                        
                        newPostalObject.idObjetoColeta__c                 = 'TF-' + String.valueOf(product.reverse_id);
                        newPostalObject.RecordTypeId                      = reverseObjectTroqueFacilRTId;

                        if(product.reason != null) {
                            // newPostalObject.Product_Reason_should_approve_Reverse__c = product.reason.should_approve;
                            newPostalObject.Product_Reason_action_Reverse__c         = product.reason.action;
                            newPostalObject.Product_Reason_description_Reverse__c    = product.reason.description;
                        }

                        postalObjectsToInsert.add(newPostalObject);

                        // campo Description no Caso deve ser preenchido com:
                        // Nome do Produto: product.name
                        // Ação Reversa do Produto: product.reverse_action
                        // Comentários do Produto: product.comments
                        // de maneira iterada

                        fullDescriptionCase += 'Nome do Produto: ' + product.name;
                        fullDescriptionCase += '\nAção Reversa do Produto: ' +  product.reverse_action;
                        fullDescriptionCase += '\nComentários do Produto: ';
                        fullDescriptionCase += (product.comments == null? 'Não há comentários sobre o produto.' : product.comments) + '\n\n';
                    }

                    newCase.description = fullDescriptionCase;
                }

                insert newCase;

                if(!postalObjectsToInsert.isEmpty()) {
                    
                    for(ObjetoPostagemReversa__c newPostalObject : postalObjectsToInsert) {
                        newPostalObject.Caso__c = newCase.Id;
                    }

                    System.debug('postalObjectsToInsert => ' + JSON.serializePretty(postalObjectsToInsert));
                    
                    insert postalObjectsToInsert;
                }
            }

        } catch (Exception e) {
            hasError = true;
        }

        IntegrationUtils.WSLog('Case (Troque Fácil)', 'Inbound', RestContext.request.requestBody.toString(), JSON.serialize(responseList), hasError);
    }

    global class TroqueFacilIN {
        public String event_name;
        public String event_date;
        public Data data;
        public String signature; // Case.Signature__c
    }

    global class Data {
        public String ecommerce_order;
        public Customer customer;
        public Reverse reverse;
    }

    global class Customer {
        public String first_name; // Case.Customer_Name__c
        public String last_name; // Case.Customer_Last_Name__c
        public String email; // Case.Customer_Email__c
        public String document; // Case.Customer_Document__c
        public String phone; // Case.Customer_Phone__c
    }

    global class Reverse {
        public Integer id; // Case.Id_Reverse__c
        public String reverse_type; // Case.Reverse_Type__c ?
        public String reverse_type_name; // Case.Reverse_Type__c ?
        public Boolean courier_collect; // Case.Courier_Collect__c
        public Integer ecommerce_order_id; // Case.Ecommerce_Order_Id__c
        // public Object order_id; // Case.Order_Id__c
        // public Object courier_data; // Case.Courier_Data__c VAZIO (NULL)
        public String total_amount; // Case.Total_Amount__c
        // public Object invoice; // Case.Invoice__c
        public String origin; // Case.Origin__c
        public Integer status_id; // Case.Status_Id__c
        public String type; // Case.Type__c
        public DestinationData destination_data; // Case.Destination__c
        public List<Product> products; // Case.Product__
        public Tracking tracking; // Case.Tracking__
        public List<Refund> refunds; // Case.Refund_Product_Requests_Reverse ??
        // public EcommerceOrder ecommerce_order; //Case.Tracking_Ecommerce_Order ??
    }

    global class Refund {
        public String type;
        public String action;
    }

    global class DestinationData {
        public String name; // Case.Destination_Name__c
        public String type; // Case.Destination_Type__c
        public String seller_id; // Case.Destination_seller_id__c
        public String seller_info; // Case.Destination_seller_info__c
        public boolean return_to_seller; // Case.Destination_return_to_seller__c
    }

    global class Product {
        public Integer order_id; // Case.Product_Order_Id_Reverse__c
        public String price; // Case.Product_Price_Reverse__c
        public String selling_price; // Case.Product_Selling_Price_Reverse__c
        public String sku; // Case.Product_SKU_Reverse__c
        public String name; // Case.Product_Name_Reverse__c
        // public Object fraud; // Case.
        // public Object situation; // Case.Product_Situation_Reverse__c
        public String protocol; // Case.Product_Protocol_Reverse__c
        public String reverse_action; // Case.Product_Reverse_Action__c
        public String comments; // Case.Product_Comments_Reverse__c
        public Reason reason;
        public Integer qty;
        public Integer requested_qty;
        public Integer received_qty;
        public Integer reverse_id; // Case.Product_Reverse_Id__c
    }

    global class Reason {
        public Boolean should_approve; //Case.Product_Reason_should_approve_Reverse__c
        public String action; //Case.Product_Reason_action_Reverse__c
        public String description; //Case.Product_Reason_description_Reverse__c
    }

    global class Tracking {
        public String expire_date; // Case.Tracking_Expire_Date__c
        public Object status; // Case.Tracking_Status__c
        public Object message; // Case.Tracking_Message__c
        public Integer id; // Case.
        public String authorization_code; // Case.Tracking_Authorization_Code__c
        public Object tracking_code; // Case.Tracking_Code__c
    }
}