force-app/main/default/objects/Encryption__c/Encryption__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Encryption</label>
</CustomObject>

force-app/main/default/objects/Encryption__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>AES chave utilizada na criptografia dos ids de registros utilizados na pesquisa de satisfação</description>
    <label>Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pesquisa_de_Satisfacao__c/Pesquisa_de_Satisfacao__c.object-meta.xml
<CustomObject>
    <label>Pesquisa de Satisfação</label>
    <nameField>
        <displayFormat>PS - {000000000}</displayFormat>
        <label>Nome de Pesquisa de Satisfação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pesquisas de Satisfação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pesquisa_de_Satisfacao__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pesquisas de Satisfação</relationshipLabel>
    <relationshipName>Pesquisas_de_Satisfacao</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PesquisaSatisfacaoControllerTest.cls
@IsTest
public with sharing class PesquisaSatisfacaoControllerTest {

    private static final TestUtils testUtilsInstance = TestUtils.getInstance();
    
    @TestSetup
    static void makeData(){
        Blob key = Crypto.generateAesKey(128);

        Encryption__c encryption = new Encryption__c(
            key__c = EncodingUtil.base64Encode(key)
        );
        insert encryption;

        Account account = testUtilsInstance.createNewAccount(null);
        insert account;

        Pesquisa_de_Satisfacao__c survey = new Pesquisa_de_Satisfacao__c(
            conta__c = account.id
        );
        insert survey;
    }

    @IsTest
    static void saveSurveyTest() {

        Blob key = EncodingUtil.base64Decode([select Id, key__c from Encryption__c LIMIT 1].key__c);

        Id surveyId = [SELECT id FROM Pesquisa_de_Satisfacao__c LIMIT 1].id;

        String encodedCipherText = EncodingUtil.base64Encode(Crypto.encryptWithManagedIV('AES128', key, Blob.valueOf(surveyId)));
        String problemSolved = 'Sim';
        String comments = 'Comentários';
        Integer rating = 5;

        PesquisaSatisfacaoController.ResponseModel response = PesquisaSatisfacaoController.saveSurvey(problemSolved, rating, encodedCipherText, comments);
        System.debug('response => ' + JSON.serializePretty(response));
    }

    @IsTest
    static void saveSurveyTestError() {

        Blob key = EncodingUtil.base64Decode([select Id, key__c from Encryption__c LIMIT 1].key__c);

        Id surveyId = [SELECT id FROM Pesquisa_de_Satisfacao__c LIMIT 1].id;

        String encodedCipherText = EncodingUtil.base64Encode(Crypto.encryptWithManagedIV('AES128', key, Blob.valueOf(surveyId)));
        String encodedId = encodingUtil.URLEncode(encodedCipherText, 'UTF-8');
        String problemSolved = 'Talvez';
        String comments = 'Comentários';
        Integer rating = 10;

        PesquisaSatisfacaoController.ResponseModel response = PesquisaSatisfacaoController.saveSurvey(problemSolved, rating, encodedId, comments);
        System.debug('response => ' + JSON.serializePretty(response));
    }

    @IsTest
    static void verifySurveyTest() {
        Blob key = EncodingUtil.base64Decode([select Id, key__c from Encryption__c LIMIT 1].key__c);

        Id surveyId = [SELECT id FROM Pesquisa_de_Satisfacao__c LIMIT 1].id;

        String encodedCipherText = EncodingUtil.base64Encode(Crypto.encryptWithManagedIV('AES128', key, Blob.valueOf(surveyId)));
        // String encodedId = encodingUtil.URLEncode(encodedCipherText, 'UTF-8');

        PesquisaSatisfacaoController.ResponseModel response = PesquisaSatisfacaoController.verifySurvey(encodedCipherText);
    }

}