force-app/main/default/objects/Encryption__c/Encryption__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Encryption</label>
</CustomObject>

force-app/main/default/objects/Encryption__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>AES chave utilizada na criptografia dos ids de registros utilizados na pesquisa de satisfação</description>
    <label>Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pesquisa_de_Satisfacao__c/Pesquisa_de_Satisfacao__c.object-meta.xml
<CustomObject>
    <label>Pesquisa de Satisfação</label>
    <nameField>
        <displayFormat>PS - {000000000}</displayFormat>
        <label>Nome de Pesquisa de Satisfação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pesquisas de Satisfação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pesquisa_de_Satisfacao__c/fields/Comentario__c.field-meta.xml
<CustomField>
    <fullName>Comentario__c</fullName>
    <description>Comentários da avaliação da pesquisa de satisfação.</description>
    <label>Comentário</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Pesquisa_de_Satisfacao__c/fields/O_seu_problema_foi_resolvido__c.field-meta.xml
<CustomField>
    <fullName>O_seu_problema_foi_resolvido__c</fullName>
    <label>O seu problema foi resolvido?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pesquisa_de_Satisfacao__c/fields/Qual_a_nota_para_este_atendimento__c.field-meta.xml
<CustomField>
    <fullName>Qual_a_nota_para_este_atendimento__c</fullName>
    <inlineHelpText>Numa escala de 1 a 5, sendo 1 Muito Insatisfeito e 5 Totalmente Satisfeito. Qual a nota para este atendimento?</inlineHelpText>
    <label>Qual a nota para este atendimento?</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pesquisa_de_Satisfacao__c/fields/Respondida__c.field-meta.xml
<CustomField>
    <fullName>Respondida__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Respondida</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PesquisaSatisfacaoController.cls
public without sharing class PesquisaSatisfacaoController {
    public PesquisaSatisfacaoController() {}

    @AuraEnabled
    public static ResponseModel verifySurvey(String encodedId){
        System.debug('encodedId => ' + encodedId);
        ResponseModel response;
        try {
            String decryptedId = decryptSurveyId(encodedId);
            System.debug('decryptedId => ' + decryptedId);
            List<Pesquisa_de_Satisfacao__c> surveyRecords = [
                SELECT id
                FROM Pesquisa_de_Satisfacao__c
                WHERE id = :decryptedId
                AND respondida__c = false
            ];
            
            if(surveyRecords.isEmpty()) {
                response = new ResponseModel('Essa pesquisa já foi respondida!', true);
            } else {
                response = new ResponseModel('Sucesso!', false);
            }
        } catch (Exception e) {
            System.debug('e.getMessage() => ' + e.getMessage());
            response = new ResponseModel('Erro: ' + e.getMessage() + ' ; ' + e.getStackTraceString(), true);
        }

        System.debug('response => ' + response);
        return response;
    }

    public static String decryptSurveyId(String encodedId) {
        Blob key = EncodingUtil.base64Decode([select Id, key__c from Encryption__c LIMIT 1].key__c);
        System.debug('key => ' + key);
        System.debug('EncodingUtil.urlEncode(encodedId, \'UTF-8\') => ' + EncodingUtil.urlEncode(encodedId, 'UTF-8'));
        Blob blobData = EncodingUtil.base64Decode(EncodingUtil.urlDecode(EncodingUtil.urlEncode(encodedId, 'UTF-8'), 'UTF-8'));
        Blob decryptedBlob = Crypto.decryptWithManagedIV('AES128', key, blobData);
        String decodedId = decryptedBlob.toString();
        System.debug('decodedId => ' + decodedId);
        return decodedId;
    }

    @AuraEnabled
    public static ResponseModel saveSurvey(String problemSolved, Integer rating, String encodedId, String observations) {
        ResponseModel response;
        System.debug('problemSolved => ' + problemSolved);
        System.debug('rating => ' + rating);
        System.debug('encodedId => ' + encodedId);

        try {
            if(encodedId != null){
                String decodedId = decryptSurveyId(encodedId);
                System.debug('decodedId => ' + decodedId);

                Pesquisa_de_Satisfacao__c pesquisaSatisfacaoRecord = new Pesquisa_de_Satisfacao__c(
                    o_seu_problema_foi_resolvido__c = problemSolved,
                    qual_a_nota_para_este_atendimento__c = rating,
                    id = decodedId,
                    respondida__c = true,
                    comentario__c = observations
                );

                update pesquisaSatisfacaoRecord;
                response = new ResponseModel('Sucesso!', false);
            }
        } catch (Exception e) {
            System.debug('e.getMessage() => ' + e.getMessage());
            response = new ResponseModel('Erro: ' + e.getMessage() + ' ; ' + e.getStackTraceString(), true);
        }

        return response;
    }

    // public class SurveyModel {
    //     public String problemSolved;
    //     public Integer rating;
    //     public String surveyRecordId;
    // }

    public class ResponseModel {
        @AuraEnabled
        public String message;
        @AuraEnabled
        public Boolean isError;

        public ResponseModel(){}

        public ResponseModel(String message, Boolean isError){
            this.message = message;
            this.isError = isError;
        }
    }
}