force-app/main/default/objects/Order/fields/OkForSending__c.field-meta.xml
<CustomField>
    <fullName>OkForSending__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Verifica se o pedido está OK (campos obrigatórios preenchidos) para o envio para Integração Pedido OUT</description>
    <label>Pronto Para Envio ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Sended__c.field-meta.xml
<CustomField>
    <fullName>Sended__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica se o pedido já foi enviado para integração Pedido OUT</description>
    <label>Enviado para Integração?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BatchIntegrationOrderOUT.cls
global class BatchIntegrationOrderOUT implements Database.Batchable<SObject>, Database.AllowsCallouts{

    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id From Pricebook2 WHERE isStandard = false LIMIT 1';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext info, List<SObject> records) {
        List<Order> listBatchOrder = [SELECT Id FROM Order];

        List<Order> listOrderOUT = new List<Order>();

        for (Order batchOrder : listBatchOrder) {
            if (batchOrder.OkForSending__c == true && batchOrder.Sended__c == false) {
                listOrderOUT.add(batchOrder);
            }
        }

        //IntegrationOrderOUT.sendOrderOUT(listOrderOUT);
    }

    public void finish(Database.BatchableContext info){

    }
}