force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email da conta PF ou PJ.</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena as Marcas cadastradas no processo da Infracommerce.</description>
    <label>Marca</label>
    <nameField>
        <label>Nome da Marca</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marcas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Brand__c/fields/TokeniHub__c.field-meta.xml
<CustomField>
    <fullName>TokeniHub__c</fullName>
    <description>Os tokens utilizados nos headers dos callouts feitos para o iHub são divididos por marca, portanto, esse campo é utilizado para armazenar o Token da Marca</description>
    <label>Token iHub</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Nota Fiscal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Relacionamento com o Pedido do Cliente.</description>
    <label>Pedido</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Order.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Casos (Pedido)</relationshipLabel>
    <relationshipName>OrderCase</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/ProtocolType__c.field-meta.xml
<CustomField>
    <fullName>ProtocolType__c</fullName>
    <description>Tipo de protocolo enviado para o iHub na Api de Protocol.
Tipos  exchange or return.</description>
    <label>Tipo de  Protocolo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NoProtocoliHub</fullName>
                <default>true</default>
                <label>Sem Protocolo Troca/Devolução</label>
            </value>
            <value>
                <fullName>return</fullName>
                <label>Devolução</label>
            </value>
            <value>
                <fullName>exchange</fullName>
                <label>Troca</label>
            </value>
            <value>
                <fullName>Ruptura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Motivo do Caso</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Status do pagamento</fullName>
            </value>
            <value>
                <fullName>Status da entrega-CD</fullName>
            </value>
            <value>
                <fullName>Status da entrega-Transporte</fullName>
            </value>
            <value>
                <fullName>Cliente atesta não conformidade</fullName>
            </value>
            <value>
                <fullName>Cliente não gostou do produto</fullName>
            </value>
            <value>
                <fullName>Status reversa</fullName>
            </value>
            <value>
                <fullName>Conta</fullName>
            </value>
            <value>
                <fullName>Erro</fullName>
            </value>
            <value>
                <fullName>Produto</fullName>
            </value>
            <value>
                <fullName>Equipe</fullName>
            </value>
            <value>
                <fullName>Localização</fullName>
            </value>
            <value>
                <fullName>Promoções</fullName>
            </value>
            <value>
                <fullName>Parceria</fullName>
            </value>
            <value>
                <fullName>Dúvidas Loja Física</fullName>
            </value>
            <value>
                <fullName>Assistência Técnica</fullName>
            </value>
            <value>
                <fullName>Institucional Marca</fullName>
            </value>
            <value>
                <fullName>SAC Infra</fullName>
            </value>
            <value>
                <fullName>SAC Terceiro</fullName>
            </value>
            <value>
                <fullName>Atendimento Loja Física</fullName>
            </value>
            <value>
                <fullName>Atendimento Distribuidor</fullName>
            </value>
            <value>
                <fullName>Atendimento NRP</fullName>
            </value>
            <value>
                <fullName>Elogio do produto</fullName>
            </value>
            <value>
                <fullName>Elogio da marca</fullName>
            </value>
            <value>
                <fullName>Elogio atendimento</fullName>
            </value>
            <value>
                <fullName>Elogio do Site</fullName>
            </value>
            <value>
                <fullName>Elogio da Logística</fullName>
            </value>
            <value>
                <fullName>Elogio de Transporte</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Telefone</fullName>
            </value>
            <value>
                <fullName>Whatsapp</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SubReason__c.field-meta.xml
<CustomField>
    <fullName>SubReason__c</fullName>
    <description>Sub-Motivo do Caso, utilizado para fins de classificação.</description>
    <label>Sub-Motivo do caso</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Reason__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pedido não aprovado</fullName>
            </value>
            <value>
                <fullName>Pedido cancelado parcial</fullName>
            </value>
            <value>
                <fullName>Pedido cancelado total</fullName>
            </value>
            <value>
                <fullName>Pedido não integrado</fullName>
            </value>
            <value>
                <fullName>Boleto não enviado</fullName>
            </value>
            <value>
                <fullName>Boleto não faturado</fullName>
            </value>
            <value>
                <fullName>Anti-fraude</fullName>
            </value>
            <value>
                <fullName>Segunda via de boleto</fullName>
            </value>
            <value>
                <fullName>Prorrogação de boleto</fullName>
            </value>
            <value>
                <fullName>Envio segunda via de nota fiscal</fullName>
            </value>
            <value>
                <fullName>Alteração de endereço</fullName>
            </value>
            <value>
                <fullName>Aguardando separação</fullName>
            </value>
            <value>
                <fullName>Aguardando faturamento</fullName>
            </value>
            <value>
                <fullName>Aguardando expedição</fullName>
            </value>
            <value>
                <fullName>Aguardando personalização</fullName>
            </value>
            <value>
                <fullName>Aguardando despacho</fullName>
            </value>
            <value>
                <fullName>Em rota dentro do prazo</fullName>
            </value>
            <value>
                <fullName>Tracking desatualizado</fullName>
            </value>
            <value>
                <fullName>Endereço insuficiente</fullName>
            </value>
            <value>
                <fullName>Endereço errado</fullName>
            </value>
            <value>
                <fullName>CEP não atendido</fullName>
            </value>
            <value>
                <fullName>Tentativa de entrega sem sucesso</fullName>
            </value>
            <value>
                <fullName>Não reconhece a entrega</fullName>
            </value>
            <value>
                <fullName>Extravio</fullName>
            </value>
            <value>
                <fullName>Retido na fiscalização</fullName>
            </value>
            <value>
                <fullName>Prazo de entrega alterado</fullName>
            </value>
            <value>
                <fullName>Em rota prazo expirado</fullName>
            </value>
            <value>
                <fullName>Tamanho grande</fullName>
            </value>
            <value>
                <fullName>Tamanho pequeno</fullName>
            </value>
            <value>
                <fullName>Não modelou bem no corpo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazenará as NFs populadas pela integração.</description>
    <label>Nota Fiscal</label>
    <nameField>
        <label>Nota Fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas Fiscais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>InvoiceNumber__c</fullName>
    <label>Número da Nota Fiscal</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Nota Fiscal</relationshipLabel>
    <relationshipName>NotaFiscal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/ObjetoPostagemReversa__c.object-meta.xml
<CustomObject>
    <description>Objeto criado para armazenar os objetos de Postagem Reversa criados para os casos de Postagem Reversa</description>
    <label>Objeto Postagem Reversa</label>
    <nameField>
        <displayFormat>OPS-{0000}</displayFormat>
        <label>Nome de Objeto Postagem Reversa</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objetos Postagem Reversa</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Objetos Postagem Reversa</relationshipLabel>
    <relationshipName>ObjetosPostagemReversa</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/OrderItem__c.field-meta.xml
<CustomField>
    <fullName>OrderItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto do pedido</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Objetos Postagem Reversa</relationshipLabel>
    <relationshipName>Objetos_Postagem_Reversa</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Marca (Loja) da Pedido</description>
    <label>Marca</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>BrandOrder</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/NumeroPedidoCliente__c.field-meta.xml
<CustomField>
    <fullName>NumeroPedidoCliente__c</fullName>
    <label>Número Pedido Cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/NumeroPedidoERP__c.field-meta.xml
<CustomField>
    <fullName>NumeroPedidoERP__c</fullName>
    <label>Número Pedido ERP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Chave Externa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup para o objeto Caso, para identificar qual produto foi trocado.</description>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Produtos do pedido</relationshipLabel>
    <relationshipName>OrderItemCase</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Sku__c.field-meta.xml
<CustomField>
    <fullName>Sku__c</fullName>
    <description>SKU ou EAN, Código de produto único.</description>
    <externalId>true</externalId>
    <label>SKU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IntegrationCaseOUT.cls
public with sharing class IntegrationCaseOUT {

    @future(callout=true)
    public static void sendCaseOUTFuture(String idCase) {
        IntegrationCaseOUT.sendCaseOUT(idCase);
    }

    public static CaseOUTResponse sendCaseOUT(String idCase) {

        CaseOUTResponse response = new CaseOUTResponse();

        Case caso = [SELECT Id, Description, Subject, CaseNumber, Reason__c, SubReason__c, Type, ProtocolType__c FROM Case WHERE id =: idCase];

        List<ObjetoPostagemReversa__c> objPostagem = [SELECT Id, OrderItem__c FROM ObjetoPostagemReversa__c WHERE Caso__c =: idCase];

        Set<Id> idsOrderItems = new Set<Id>();
        for (ObjetoPostagemReversa__c postagemReversa : objPostagem) {
            idsOrderItems.add(postagemReversa.OrderItem__c);
        }

        String idOrder = [SELECT Id, Order__c FROM Case WHERE Id =: idCase].Order__c;

        Order order = [ SELECT Id, NumeroPedidoERP__c, NumeroPedidoCliente__c, Name, AccountId, Account.Name, Account.ExternalId__c, 
                            Account.Email__c, Account.Phone, Account.CPF__c, Account.CNPJ__c, Brand__c, Brand__r.TokeniHub__c
                        FROM Order
                        WHERE Id =: idOrder];

        Account account = order.Account;
                        
        Invoice__c invoice;

        List<Invoice__c> listInvoice = [SELECT Id, Order__c, InvoiceNumber__c FROM Invoice__c WHERE Order__c =: idOrder];

        if(listInvoice.size() > 0){
            invoice = listInvoice.get(0);
        }
        System.debug('invoice ' + invoice);

        List<OrderItem> listOrderItems;
        
        if(caso.ProtocolType__c == 'exchange') {
            listOrderItems = [SELECT Id, Sku__c, Quantity, UnitPrice, OrderId FROM OrderItem WHERE OrderId =: idOrder];
        } else {
            listOrderItems = [SELECT Id, Sku__c, Quantity, UnitPrice, OrderId FROM OrderItem WHERE Id IN: idsOrderItems];
        }

        TemplateDataIntegrationFields.AccountCaseOUTData accountOUT           = new TemplateDataIntegrationFields.AccountCaseOUTData(account);
        List<TemplateDataIntegrationFields.ItemsCaseOUTData> listItemsCaseOUT = new List<TemplateDataIntegrationFields.ItemsCaseOUTData>();

        for (OrderItem orderItem : listOrderItems) {
            TemplateDataIntegrationFields.ItemsCaseOUTData itemCaseOUT = new TemplateDataIntegrationFields.ItemsCaseOUTData(orderItem);
            listItemsCaseOUT.add(itemCaseOUT);
        }
        System.debug('invoice ' + invoice);

        Http conexao     = new Http();
        HttpRequest req = new HttpRequest();

        String endpoint  = [SELECT Id, Endpoint_iHub__c FROM GeneralSetting__mdt LIMIT 1].Endpoint_iHub__c;
        //String token     = [SELECT Id, Token_iHub__c    FROM GeneralSetting__mdt LIMIT 1].Token_iHub__c;
        // String token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiaW50ZWdyYXRpb24iLCJzdG9yZXMiOlsiNWJkMTBkZDYxOWM1MmIwMDI3YWQyOWE1Il0sImFjdGl2ZSI6dHJ1ZSwiYWNsIjpbIkludGVncmF0aW9uIl0sIl9pZCI6IjYxNTQ5N2U0MjY0YmQyMDAxMmNlMDNkZiIsImNyZWF0ZWRCeSI6IjVkOTRmODdjYTc1OGFkMDAxMWRkYjk2ZSIsIm5hbWUiOiJQcm90b2NvbG8gU2FsZXNmb3JjZSIsIm9yaWdpbiI6InRyb2NhLWZhY2lsIiwiaWF0IjoxNjMyOTMzODYwfQ.Lfj6R0pcD3HdLnPTeqzTRg09tRX5Hu39kvuFvrCULbA';
        String token;

        if(order.brand__c == null) {
            response.hasError   = true;
            response.message    = 'Não foi possível integrar com o ERP pois o Pedido não possui marca. Favor verificar com o administrador.';
        } else if (order.brand__r.TokeniHub__c == null) {
            response.hasError   = true;
            response.message    = 'Não foi possível integrar com o ERP pois a marca do pedido não possui o token necessário para integrar com o ERP. Favor verificar com o administrador.';
        } else {
            // token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiaW50ZWdyYXRpb24iLCJzdG9yZXMiOlsiNWU4YjhlYTgyMTRmNWQwMDE5ZjMwNzQxIl0sImFjdGl2ZSI6dHJ1ZSwiYWNsIjpbIkludGVncmF0aW9uIl0sIl9pZCI6IjYxOTUzYTk1MDM0MDMyMDAxMmJhOTNmYyIsImNyZWF0ZWRCeSI6IjVkODIxNjQ1ZmViMWJjMDAxMTRkOTM3YyIsIm5hbWUiOiJJbnRlZ3JhdGlvbiIsIm9yaWdpbiI6ImlodWIiLCJpYXQiOjE2MzcxNjk4MTN9.eQix8Uj3uhaXTGpoMroOgXqshfiG5_WM6xj4fHhHT8g';
            token = order.brand__r.TokeniHub__c;
        }

        //req.setEndpoint('https://enae1e1qmbgjmqv.m.pipedream.net');

        String body;

        if(caso.ProtocolType__c == 'exchange') {
            
            TemplateDataIntegrationFields.ExchangeCaseOUTData exchangeCaseOUT = new TemplateDataIntegrationFields.ExchangeCaseOUTData(invoice, order, caso);
            exchangeCaseOUT.customer = accountOUT;
            exchangeCaseOUT.items    = listItemsCaseOUT;
            System.debug('Custumer ' + exchangeCaseOUT.customer);
            System.debug('Items ' + exchangeCaseOUT.items);
            System.debug('CaseOUT ' + exchangeCaseOUT);

            body = JSON.serialize(exchangeCaseOUT);
        
        } else {

            TemplateDataIntegrationFields.CaseOUTData caseOUT = new TemplateDataIntegrationFields.CaseOUTData(invoice, order, caso);
            caseOUT.customer = accountOUT;
            caseOUT.items    = listItemsCaseOUT;
            System.debug('Custumer ' + caseOUT.customer);
            System.debug('Items ' + caseOUT.items);
            System.debug('CaseOUT ' + caseOUT);
            
            body = JSON.serialize(caseOUT);
        }

        req.setEndpoint(endpoint + '/orders/protocols');
        req.setHeader('Authorization', 'Bearer ' + token);
        req.setHeader('Content-Type', 'application/json');
        req.setBody(body);
        req.setMethod('POST');

        HttpResponse resp = conexao.send(req);

        System.debug('resp => ' + resp);
        System.debug('resp.getStatusCode() => ' + resp.getStatusCode());
        System.debug('resp.getBody() => ' + JSON.serialize(resp.getBody()));

        if (resp.getStatusCode() == 201) {
            response.hasError = false;
            response.statusCode = resp.getStatusCode();

            response.message = resp.getBody();

            System.debug('DEU CERTO ' + resp.getStatusCode());
            IntegrationUtils.WSLog('Protocol Out', 'Outbound', body, resp.getBody(), false);
        } else {
            response.hasError = true;
            response.statusCode = resp.getStatusCode();

            response.message = resp.getBody();
            System.debug('STATUS CODE ' + resp.getStatusCode());
            System.debug('Body ' + JSON.serialize(resp.getBody()));
            IntegrationUtils.WSLog('Protocol Out', 'Outbound', body, resp.getBody(), false);
        }

        return response;
    }

    public class CaseOUTResponse {
        public String message;
        public Boolean hasError;
        public Integer statusCode;

        public CaseOUTResponse(){}

        public CaseOUTResponse(Boolean hasError, String message, Integer statusCode){
            this.hasError = hasError;
            this.message = message;
            this.statusCode = statusCode;
        }
    }
}