force-app/main/default/objects/Account/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email da conta PF ou PJ.</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena os múltiplos endereços da conta.</description>
    <label>Endereço</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Endereço</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Endereços</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Relacionamento com o objeto Conta.</description>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Endereços</relationshipLabel>
    <relationshipName>AccountAddress</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Campo com o Endereço completo de Cobrança.</description>
    <formula>ReceiverName__c &amp; BR() &amp; 
Street__c &amp; &quot;, &quot; &amp; Number__c &amp; BR() &amp; 
Neighborhood__c &amp; &quot; - &quot; &amp; &quot;CEP: &quot; &amp; PostalCode__c &amp; BR() &amp;
City__c  &amp; &quot;/&quot; &amp; TEXT(State__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Endereço Completo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/AddressType__c.field-meta.xml
<CustomField>
    <fullName>AddressType__c</fullName>
    <label>Tipo de endereço</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
                <default>true</default>
                <label>Casa</label>
            </value>
            <value>
                <fullName>Commercial</fullName>
                <label>Comercial</label>
            </value>
            <value>
                <fullName>Apartment</fullName>
                <label>Apartamento</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <label>Outro</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Campo Cidade do Endereço de Cobrança.</description>
    <label>Cidade</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>País do Endereço de Cobrança.</description>
    <label>País</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Chave Externa</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Address__c/fields/Neighborhood__c.field-meta.xml
<CustomField>
    <fullName>Neighborhood__c</fullName>
    <description>Bairro do Endereço</description>
    <label>Bairro</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/ReceiverName__c.field-meta.xml
<CustomField>
    <fullName>ReceiverName__c</fullName>
    <description>Nome do destinatário.</description>
    <label>Nome do destinatário</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Campo de Estado do Endereço de Cobrança.</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Campo Rua do Endereço de Cobrança.</description>
    <label>Rua</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena as Marcas cadastradas no processo da Infracommerce.</description>
    <label>Marca</label>
    <nameField>
        <label>Nome da Marca</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marcas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>Determina se o registro está ativo ou não.</description>
    <label>Ativo ?</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Ativo</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <label>Inativo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand__c/fields/BusinessName__c.field-meta.xml
<CustomField>
    <fullName>BusinessName__c</fullName>
    <description>Nome Comercial da Marca que será usado nos templates de e-mails por exemplo.</description>
    <inlineHelpText>Insira o nome Comercial que será utilizado em templates de e-mail, contato com o consumidor e relatórios.</inlineHelpText>
    <label>Nome Comercial</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brand__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Brand__c/fields/TokeniHub__c.field-meta.xml
<CustomField>
    <fullName>TokeniHub__c</fullName>
    <description>Os tokens utilizados nos headers dos callouts feitos para o iHub são divididos por marca, portanto, esse campo é utilizado para armazenar o Token da Marca</description>
    <label>Token iHub</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Brand__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Tipo do cadastro da Marca.</description>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipos_de_Marcas</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Centro_de_Distribuicao__c/Centro_de_Distribuicao__c.object-meta.xml
<CustomObject>
    <label>Centro de Distribuição</label>
    <nameField>
        <label>Nome de Centro de Distribuição</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centros de Distribuição</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Centro_de_Distribuicao__c/fields/BairroCD__c.field-meta.xml
<CustomField>
    <fullName>BairroCD__c</fullName>
    <label>Bairro</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Centro_de_Distribuicao__c/fields/BairroReversa__c.field-meta.xml
<CustomField>
    <fullName>BairroReversa__c</fullName>
    <label>Bairro</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Centro_de_Distribuicao__c/fields/CD__c.field-meta.xml
<CustomField>
    <fullName>CD__c</fullName>
    <label>CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Centro_de_Distribuicao__c/fields/CepCD__c.field-meta.xml
<CustomField>
    <fullName>CepCD__c</fullName>
    <label>CEP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Centro_de_Distribuicao__c/fields/CepReversa__c.field-meta.xml
<CustomField>
    <fullName>CepReversa__c</fullName>
    <label>CEP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Centro_de_Distribuicao__c/fields/CidadeCD__c.field-meta.xml
<CustomField>
    <fullName>CidadeCD__c</fullName>
    <label>Cidade</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Centro_de_Distribuicao__c/fields/CidadeReversa__c.field-meta.xml
<CustomField>
    <fullName>CidadeReversa__c</fullName>
    <label>Cidade</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Centro_de_Distribuicao__c/fields/Endereco__c.field-meta.xml
<CustomField>
    <fullName>Endereco__c</fullName>
    <label>Endereço</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Centro_de_Distribuicao__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do CD (SellerCode)</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Centro_de_Distribuicao__c/fields/UFCD__c.field-meta.xml
<CustomField>
    <fullName>UFCD__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Centro_de_Distribuicao__c/fields/UFReversa__c.field-meta.xml
<CustomField>
    <fullName>UFReversa__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/LogisticInformation__c/LogisticInformation__c.object-meta.xml
<CustomObject>
    <label>Informação Logística</label>
    <nameField>
        <label>Nome de Informação Logística</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Informações Logísticas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LogisticInformation__c/fields/address__c.field-meta.xml
<CustomField>
    <fullName>address__c</fullName>
    <label>Endereço</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogisticInformation__c/fields/deliveryCompany__c.field-meta.xml
<CustomField>
    <fullName>deliveryCompany__c</fullName>
    <label>Empresa de Entrega</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogisticInformation__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/LogisticInformation__c/fields/listPrice__c.field-meta.xml
<CustomField>
    <fullName>listPrice__c</fullName>
    <label>Lista de Preço</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/LogisticInformation__c/fields/logisticContract__c.field-meta.xml
<CustomField>
    <fullName>logisticContract__c</fullName>
    <label>Contrato Logístico</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogisticInformation__c/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <label>Pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Informações Logísticas</relationshipLabel>
    <relationshipName>Informacoes_Logisticas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LogisticInformation__c/fields/price__c.field-meta.xml
<CustomField>
    <fullName>price__c</fullName>
    <label>Preço</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/LogisticInformation__c/fields/sellingPrice__c.field-meta.xml
<CustomField>
    <fullName>sellingPrice__c</fullName>
    <label>Preço de Venda</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Marca (Loja) da Pedido</description>
    <label>Marca</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>BrandOrder</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/CentrodeDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentrodeDistribuicao__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centro de Distribuição</label>
    <lookupFilter>
        <active>false</active>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Centro_de_Distribuicao__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>CDPedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Endereco__c.field-meta.xml
<CustomField>
    <fullName>Endereco__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Endereço</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/IntegrationOrderOUTTest.cls
@isTest
public with sharing class IntegrationOrderOUTTest {

    @isTest
    public static void sendOrderOUT () {
        Brand__c marcaTest        = new Brand__c();
        marcaTest.Name            = 'Test';
        marcaTest.Active__c       = 'Active';
        marcaTest.BusinessName__c = 'Marca de Test';
        marcaTest.ExternalId__c   = 'TEST';
        marcaTest.Type__c         = 'B2B';
        marcaTest.TokeniHub__c   = 'TokenTest023i01j0aijr083j0q8f4hja08';
        insert marcaTest;

        Centro_de_Distribuicao__c cdTest = new Centro_de_Distribuicao__c();
        cdTest.Name             = 'Test';
        cdTest.BairroCD__c      = 'Bairro';
        cdTest.BairroReversa__c = 'Bairro Reversa';
        cdTest.CD__c            = 'DCR';
        cdTest.CepCD__c         = '01153-000';
        cdTest.CepReversa__c    = '86010-360';
        cdTest.CidadeCD__c      = 'São Paulo';
        cdTest.CidadeReversa__c = 'Londrina';
        cdTest.UFCD__c          = 'SP';
        cdTest.UFReversa__c     = 'PR';
        cdTest.ExternalId__c    = 'text-classe';
        insert cdTest;

        Account accountTest       = new Account();
        accountTest.Name          = 'AccountTest';
        accountTest.ExternalId__c = '123456';
        accountTest.Email__c      = 'accountTest@gmail.com';
        accountTest.CPF__c        = '12835170006';
        accountTest.Phone         = '11999999999';
        insert accountTest;

        Address__c addressTest      = new Address__c();
        addressTest.Account__c      = accountTest.Id;
        addressTest.AddressType__c  = 'Residencial';
        addressTest.City__c         = 'Londrina';
        addressTest.Country__c      = 'Brasil';
        addressTest.Neighborhood__c = 'Centro';
        addressTest.State__c        = 'PR';
        addressTest.Street__c       = 'Av. Higienópolis';
        addressTest.ReceiverName__c = 'Test';
        insert addressTest;

        Order orderTest                   = new Order();
        //orderTest.ExternalId__c           = '123456';
        orderTest.AccountId               = accountTest.Id;
        orderTest.CentrodeDistribuicao__c = cdTest.Id;
        orderTest.Brand__c                = marcaTest.Id;
        orderTest.Endereco__c             = addressTest.Id;
        orderTest.EffectiveDate           = date.parse('05/11/2021');
        orderTest.Status                  = 'invoiced';
        insert orderTest;

        LogisticInformation__c logisticInformationTest = new LogisticInformation__c();
        logisticInformationTest.ExternalId__c          = '123456789TEST';
        logisticInformationTest.logisticContract__c    = 'Test';
        logisticInformationTest.price__c               = 7;
        logisticInformationTest.sellingPrice__c        = 7;
        logisticInformationTest.listPrice__c           = 7;
        logisticInformationTest.deliveryCompany__c     = 'Test LTDA';
        logisticInformationTest.Pedido__c              =  orderTest.Id;
        insert logisticInformationTest;

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new IntegrationOrderOUTMock());
        IntegrationOrderOUT.sendOrderOUT(orderTest.Id);
        Test.stopTest();
    }
}