force-app/main/default/objects/Account/fields/documentType__c.field-meta.xml
<CustomField>
    <fullName>documentType__c</fullName>
    <label>Tipo de Documento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena as Marcas cadastradas no processo da Infracommerce.</description>
    <label>Marca</label>
    <nameField>
        <label>Nome da Marca</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marcas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Brand__c/fields/TokeniHub__c.field-meta.xml
<CustomField>
    <fullName>TokeniHub__c</fullName>
    <description>Os tokens utilizados nos headers dos callouts feitos para o iHub são divididos por marca, portanto, esse campo é utilizado para armazenar o Token da Marca</description>
    <label>Token iHub</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/AccountType__c.field-meta.xml
<CustomField>
    <fullName>AccountType__c</fullName>
    <label>Tipo de Conta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>currentAccount</fullName>
                <label>Conta Corrente</label>
            </value>
            <value>
                <fullName>savingsAccount</fullName>
                <label>Conta Poupança</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Agencia__c.field-meta.xml
<CustomField>
    <fullName>Agencia__c</fullName>
    <label>Agência</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/BankCode__c.field-meta.xml
<CustomField>
    <fullName>BankCode__c</fullName>
    <formula>Bank__r.BankCode__c</formula>
    <label>Código de Banco</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ContaCorrente__c.field-meta.xml
<CustomField>
    <fullName>ContaCorrente__c</fullName>
    <label>Conta Corrente</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/DigitoConta__c.field-meta.xml
<CustomField>
    <fullName>DigitoConta__c</fullName>
    <label>Dígito Conta</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/DocumentType__c.field-meta.xml
<CustomField>
    <fullName>DocumentType__c</fullName>
    <description>Tipo de documento da conta para reembolso. CPF ou CNPJ.</description>
    <inlineHelpText>Tipo de documento da conta para reembolso. CPF ou CNPJ.</inlineHelpText>
    <label>Tipo de Documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>cpf</fullName>
                <label>Cpf</label>
            </value>
            <value>
                <fullName>cnpj</fullName>
                <label>Cnpj</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Relacionamento com o Pedido do Cliente.</description>
    <label>Pedido</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Order.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Casos (Pedido)</relationshipLabel>
    <relationshipName>OrderCase</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/ReassignCase__c.field-meta.xml
<CustomField>
    <fullName>ReassignCase__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo que define se o caso será reatribuido.</description>
    <label>ReatribuirCaso</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/RefundId__c.field-meta.xml
<CustomField>
    <fullName>RefundId__c</fullName>
    <label>Id do Estorno Automático</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GeneralSetting__mdt/GeneralSetting__mdt.object-meta.xml
<CustomObject>
    <label>General Setting</label>
    <pluralLabel>General Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/GeneralSetting__mdt/fields/Endpoint_iHub__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_iHub__c</fullName>
    <label>Endpoint iHub</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GeneralSetting__mdt/fields/Token_iHub__c.field-meta.xml
<CustomField>
    <fullName>Token_iHub__c</fullName>
    <label>Token iHub</label>
    <length>400</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/ObjetoPostagemReversa__c.object-meta.xml
<CustomObject>
    <description>Objeto criado para armazenar os objetos de Postagem Reversa criados para os casos de Postagem Reversa</description>
    <label>Objeto Postagem Reversa</label>
    <nameField>
        <displayFormat>OPS-{0000}</displayFormat>
        <label>Nome de Objeto Postagem Reversa</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objetos Postagem Reversa</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Objetos Postagem Reversa</relationshipLabel>
    <relationshipName>ObjetosPostagemReversa</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/OrderItem__c.field-meta.xml
<CustomField>
    <fullName>OrderItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto do pedido</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Objetos Postagem Reversa</relationshipLabel>
    <relationshipName>Objetos_Postagem_Reversa</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/Product_Selling_Price_Reverse__c.field-meta.xml
<CustomField>
    <fullName>Product_Selling_Price_Reverse__c</fullName>
    <label>Preço de Venda Produto Reversa</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Marca (Loja) da Pedido</description>
    <label>Marca</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>BrandOrder</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Grupo__c.field-meta.xml
<CustomField>
    <fullName>Grupo__c</fullName>
    <description>Campo de forma de pagamento que é populado através de integração do Objeto de Payments__c, campo Grupo__c.</description>
    <label>Forma de Pagamento</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>bankInvoice</fullName>
                <label>Boleto Bancário</label>
            </value>
            <value>
                <fullName>creditCard</fullName>
                <label>Cartão de Crédito</label>
            </value>
            <value>
                <fullName>external</fullName>
                <label>Parceiro</label>
            </value>
            <value>
                <fullName>giftCard</fullName>
                <label>Cartão Presente</label>
            </value>
            <value>
                <fullName>debitCard</fullName>
                <label>Cartão de Débito</label>
            </value>
            <value>
                <fullName>payPal</fullName>
                <label>PayPal</label>
            </value>
            <value>
                <fullName>promissory</fullName>
                <label>Boleto Faturado</label>
            </value>
            <value>
                <fullName>creditControl</fullName>
            </value>
            <value>
                <fullName>exchange</fullName>
                <label>Troca</label>
            </value>
            <value>
                <fullName>return</fullName>
                <label>Devolução</label>
            </value>
            <value>
                <fullName>instantPayment</fullName>
                <label>PIX</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/NumeroPedidoERP__c.field-meta.xml
<CustomField>
    <fullName>NumeroPedidoERP__c</fullName>
    <label>Número Pedido ERP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Chave Externa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup para o objeto Caso, para identificar qual produto foi trocado.</description>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Produtos do pedido</relationshipLabel>
    <relationshipName>OrderItemCase</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payments__c/Payments__c.object-meta.xml
<CustomObject>
    <label>Dados de Pagamento</label>
    <nameField>
        <label>Nome de Dados de Pagamento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dados de Pagamento</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payments__c/fields/Grupo__c.field-meta.xml
<CustomField>
    <fullName>Grupo__c</fullName>
    <label>Forma de Pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>bankInvoice</fullName>
                <label>Boleto Bancário</label>
            </value>
            <value>
                <fullName>creditCard</fullName>
                <label>Cartão de Crédito</label>
            </value>
            <value>
                <fullName>external</fullName>
                <label>Parceiro</label>
            </value>
            <value>
                <fullName>giftCard</fullName>
                <label>Cartão Presente</label>
            </value>
            <value>
                <fullName>debitCard</fullName>
                <label>Cartão de Débito</label>
            </value>
            <value>
                <fullName>payPal</fullName>
                <label>PayPal</label>
            </value>
            <value>
                <fullName>promissory</fullName>
                <label>Boleto Faturado</label>
            </value>
            <value>
                <fullName>creditControl</fullName>
            </value>
            <value>
                <fullName>exchange</fullName>
                <label>Troca</label>
            </value>
            <value>
                <fullName>return</fullName>
                <label>Devolução</label>
            </value>
            <value>
                <fullName>instantPayment</fullName>
                <label>PIX</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payments__c/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <label>Pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Dados de Pagamento</relationshipLabel>
    <relationshipName>Dados_de_Pagamento</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payments__c/fields/value__c.field-meta.xml
<CustomField>
    <fullName>value__c</fullName>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/IntegrationRefundOUT.cls
public with sharing class IntegrationRefundOUT {
    public IntegrationRefundOUT() {}

    @future(callout=true)
    public static void sendRefundOUTFuture(String idCase) {
        sendRefundOUT(idCase);
    }

    public static RefundOUTResponse sendRefundOUT(String idCase) {
        RefundOUTResponse response = new RefundOUTResponse();

        TemplateDataIntegrationFields.RefundOUTData refundOUTData = new TemplateDataIntegrationFields.RefundOUTData();

        Case caseObj = [
            SELECT  Id, CaseNumber, AccountId, Account.ExternalId__c, Account.DocumentType__c,
                    Order__c, Order__r.Brand__c, Order__r.Brand__r.TokeniHub__c, BankCode__c,
                    ContaCorrente__c, DigitoConta__c, AccountType__c, Agencia__c, Status, ReassignCase__c,
                    Account.Name, Order__r.NumeroPedidoERP__c
            FROM Case 
            WHERE id =: idCase
        ];

        List<Payments__c> paymentMethods = [
            SELECT id, grupo__c, value__c 
            FROM Payments__c 
            WHERE pedido__c =: caseObj.order__c
        ];

        List<ObjetoPostagemReversa__c> itensPostagemReversa = [
            SELECT id, OrderItem__c, OrderItem__r.TotalPrice, Caso__c, Product_Selling_Price_Reverse__c  
            FROM ObjetoPostagemReversa__c 
            WHERE Caso__c =: caseObj.Id
        ];

        Decimal sumPrice = 0; 
        for(ObjetoPostagemReversa__c objPostReversa : itensPostagemReversa) {
            if(objPostReversa.OrderItem__r.TotalPrice != null){
                sumPrice += objPostReversa.OrderItem__r.TotalPrice;
            } else {
                sumPrice += objPostReversa.Product_Selling_Price_Reverse__c;
            }
        }

        refundOUTData.type          = paymentMethods[0].grupo__c;
        refundOUTData.protocol      = caseObj.CaseNumber;
        // refundOUTData.refundValue   = paymentMethods[0].value__c;
        refundOUTData.refundValue   = sumPrice;
        refundOUTData.originOrderId = caseObj.order__r.NumeroPedidoERP__c;

        // if(paymentMethods[0].grupo__c == 'bankInvoice') {

        //     if( String.isBlank(caseObj.ContaCorrente__c) || 
        //         String.isBlank(caseObj.DigitoConta__c) || 
        //         String.isBlank(caseObj.AccountType__c) || 
        //         String.isBlank(caseObj.Agencia__c) || 
        //         String.isBlank(caseObj.BankCode__c)
        //     ) {
        //         response.hasError   = true;
        //         response.message    = 'Estão faltando informações bancárias no Caso.';

        //         return response;
        //     }
        //     TemplateDataIntegrationFields.BankInvoiceOUTData bankAccountOUTData = new TemplateDataIntegrationFields.BankInvoiceOUTData();
        //     bankAccountOUTData.account      = caseObj.ContaCorrente__c; //bank account
        //     bankAccountOUTData.accountDigit = caseObj.DigitoConta__c; //bank account digit
        //     bankAccountOUTData.accountType  = caseObj.AccountType__c; //bank account type
        //     bankAccountOUTData.bankAgency   = caseObj.Agencia__c; //bank account agency
        //     bankAccountOUTData.bankCode     = caseObj.BankCode__c; //bank account code
        //     bankAccountOUTData.customerName = caseObj.Account.Name;
        //     // bankAccountOUTData.document     = caseObj.Account.ExternalId__c;
        //     // bankAccountOUTData.documentType = caseObj.Account.DocumentType__c;
        //     String documentFormated = String.valueOf(caseObj.Account.ExternalId__c);
        //     System.debug('documentFormated ' + documentFormated);
        //     bankAccountOUTData.document     = caseObj.Account.DocumentType__c == 'cpf'? documentFormated.substring(0,3) + '.' + documentFormated.substring(3,6) + '.' + documentFormated.substring(6,9) + '-' + documentFormated.substring(9,11) : 
        //                                                                                 documentFormated.substring(0,2) + '.' + documentFormated.substring(2,5) + '.' + documentFormated.substring(5,8) + '/' + documentFormated.substring(8,12)  + '-' + documentFormated.substring(12,14); 
        //     bankAccountOUTData.documentType = caseObj.Account.DocumentType__c;


        //     refundOUTData.bankAccount = bankAccountOUTData;
        // } else
        if(paymentMethods[0].grupo__c == 'creditCard') {

            TemplateDataIntegrationFields.BankAccountOUTData bankAccountOUTData = new TemplateDataIntegrationFields.BankAccountOUTData();
            // bankAccountOUTData.document = caseObj.Account.ExternalId__c;

            String documentFormated = String.valueOf(caseObj.Account.ExternalId__c);
            bankAccountOUTData.document     = caseObj.Account.DocumentType__c == 'cpf'? documentFormated.substring(0,3) + '.' + documentFormated.substring(3,6) + '.' + documentFormated.substring(6,9) + '-' + documentFormated.substring(9,11) : 
                                                                                        documentFormated.substring(0,2) + '.' + documentFormated.substring(2,5) + '.' + documentFormated.substring(5,8) + '/' + documentFormated.substring(8,12)  + '-' + documentFormated.substring(12,14); 
            refundOUTData.bankAccount       = bankAccountOUTData;
        }

        Http httpConection = new Http();
        HttpRequest resq   = new HttpRequest();

        String endpoint = [SELECT Id, Endpoint_iHub__c FROM GeneralSetting__mdt LIMIT 1].Endpoint_iHub__c;
        // String token    = [SELECT Id, Token_iHub__c    FROM GeneralSetting__mdt LIMIT 1].Token_iHub__c;
        String token;

        if(caseObj.order__r.brand__c == null) {
            response.hasError   = true;
            response.message    = 'Não foi possível integrar com o ERP pois o Pedido não possui marca. Favor verificar com o administrador.';
        } else if (caseObj.order__r.brand__r.TokeniHub__c == null) {
            response.hasError   = true;
            response.message    = 'Não foi possível integrar com o ERP pois a marca do pedido não possui o token necessário para integrar com o ERP. Favor verificar com o administrador.';
        } else {
            // token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiaW50ZWdyYXRpb24iLCJzdG9yZXMiOlsiNWU4YjhlYTgyMTRmNWQwMDE5ZjMwNzQxIl0sImFjdGl2ZSI6dHJ1ZSwiYWNsIjpbIkludGVncmF0aW9uIl0sIl9pZCI6IjYxOTUzYTk1MDM0MDMyMDAxMmJhOTNmYyIsImNyZWF0ZWRCeSI6IjVkODIxNjQ1ZmViMWJjMDAxMTRkOTM3YyIsIm5hbWUiOiJJbnRlZ3JhdGlvbiIsIm9yaWdpbiI6ImlodWIiLCJpYXQiOjE2MzcxNjk4MTN9.eQix8Uj3uhaXTGpoMroOgXqshfiG5_WM6xj4fHhHT8g';
            token = caseObj.order__r.brand__r.TokeniHub__c;
        }

        System.debug('endpoint ' + endpoint + '/finance/refunds');
        System.debug('token ' + token);
        System.debug('body ' + JSON.serializePretty(refundOUTData));
        System.debug('body ' + JSON.serialize(refundOUTData));

        resq.setEndpoint(endpoint + '/finance/refunds');
        //resq.setEndpoint('https://enae1e1qmbgjmqv.m.pipedream.net');
        
        resq.setHeader('Authorization', 'Bearer ' + token);
        resq.setHeader('Content-Type', 'application/json');
        resq.setBody(JSON.serialize(refundOUTData));
        resq.setMethod('POST');

        HttpResponse retorno = httpConection.send(resq);

        response.statusCode = retorno.getStatusCode();
        response.hasError   = response.statusCode != 200? true : false;
        response.message    = retorno.getBody();

        System.debug('status code ' + retorno.getStatusCode());
        System.debug('retorno ' + retorno.getStatus());
        System.debug('body ' + retorno.getBody());
        System.debug('body ' + JSON.serializePretty(retorno.getBody()));
        
        if (retorno.getStatusCode() == 200) {
            System.debug('retorno ok');
            IntegrationUtils.WSLog('Refund Out', 'Outbound', retorno.getBody(), JSON.serialize(refundOUTData), false);
            Map<String, Object> deserializedBody = (Map<String, Object>) JSON.deserializeUntyped(retorno.getBody());
            String refundId = String.valueOf(deserializedBody.get('_id'));
            caseObj.RefundId__c = refundId;

        } else {

            caseObj.Status = 'New';
            caseObj.ReassignCase__c = true;

            IntegrationUtils.WSLog('Refund Out', 'Outbound', retorno.getBody(), JSON.serialize(refundOUTData), true);
        }

        try {

            Boolean previousTriggerState = CaseTriggerHandler.isTriggerEnabled();
            CaseTriggerHandler.disableTrigger();
                update caseObj;
            if(previousTriggerState) {
                CaseTriggerHandler.enableTrigger();
            }
        } catch (Exception e) {
            System.debug('e => ' + e.getMessage());
        }

        return response;
    }

    public class RefundOUTResponse {
        public String message;
        public Boolean hasError;
        public Integer statusCode;

        public RefundOUTResponse(){}

        public RefundOUTResponse(Boolean hasError, String message, Integer statusCode){
            this.hasError = hasError;
            this.message = message;
            this.statusCode = statusCode;
        }
    }
}