force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email da conta PF ou PJ.</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena os múltiplos endereços da conta.</description>
    <label>Endereço</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Endereço</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Endereços</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Relacionamento com o objeto Conta.</description>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Endereços</relationshipLabel>
    <relationshipName>AccountAddress</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Campo com o Endereço completo de Cobrança.</description>
    <formula>ReceiverName__c &amp; BR() &amp; 
Street__c &amp; &quot;, &quot; &amp; Number__c &amp; BR() &amp; 
Neighborhood__c &amp; &quot; - &quot; &amp; &quot;CEP: &quot; &amp; PostalCode__c &amp; BR() &amp;
City__c  &amp; &quot;/&quot; &amp; TEXT(State__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Endereço Completo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Campo Cidade do Endereço de Cobrança.</description>
    <label>Cidade</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Complement__c.field-meta.xml
<CustomField>
    <fullName>Complement__c</fullName>
    <description>Complemento do Endereço.</description>
    <label>Complemento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>País do Endereço de Cobrança.</description>
    <label>País</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Chave Externa</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Address__c/fields/Neighborhood__c.field-meta.xml
<CustomField>
    <fullName>Neighborhood__c</fullName>
    <description>Bairro do Endereço</description>
    <label>Bairro</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <description>Número do endereço.</description>
    <label>Número</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <description>Campo de CEP do Endereço (Postal Code)</description>
    <label>CEP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/ReceiverName__c.field-meta.xml
<CustomField>
    <fullName>ReceiverName__c</fullName>
    <description>Nome do destinatário.</description>
    <label>Nome do destinatário</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Campo de Estado do Endereço de Cobrança.</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Campo Rua do Endereço de Cobrança.</description>
    <label>Rua</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena as Marcas cadastradas no processo da Infracommerce.</description>
    <label>Marca</label>
    <nameField>
        <label>Nome da Marca</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marcas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/NumeroColeta__c.field-meta.xml
<CustomField>
    <fullName>NumeroColeta__c</fullName>
    <label>Número do E-Ticket</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Relacionamento com o Pedido do Cliente.</description>
    <label>Pedido</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Order.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Casos (Pedido)</relationshipLabel>
    <relationshipName>OrderCase</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/ProtocolType__c.field-meta.xml
<CustomField>
    <fullName>ProtocolType__c</fullName>
    <description>Tipo de protocolo enviado para o iHub na Api de Protocol.
Tipos  exchange or return.</description>
    <label>Tipo de  Protocolo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NoProtocoliHub</fullName>
                <default>true</default>
                <label>Sem Protocolo Troca/Devolução</label>
            </value>
            <value>
                <fullName>return</fullName>
                <label>Devolução</label>
            </value>
            <value>
                <fullName>exchange</fullName>
                <label>Troca</label>
            </value>
            <value>
                <fullName>Ruptura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Centro_de_Distribuicao__c/Centro_de_Distribuicao__c.object-meta.xml
<CustomObject>
    <label>Centro de Distribuição</label>
    <nameField>
        <label>Nome de Centro de Distribuição</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centros de Distribuição</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Centro_de_Distribuicao__c/fields/BairroReversa__c.field-meta.xml
<CustomField>
    <fullName>BairroReversa__c</fullName>
    <label>Bairro</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Centro_de_Distribuicao__c/fields/CepReversa__c.field-meta.xml
<CustomField>
    <fullName>CepReversa__c</fullName>
    <label>CEP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Centro_de_Distribuicao__c/fields/CidadeReversa__c.field-meta.xml
<CustomField>
    <fullName>CidadeReversa__c</fullName>
    <label>Cidade</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Centro_de_Distribuicao__c/fields/ComplementoReversa__c.field-meta.xml
<CustomField>
    <fullName>ComplementoReversa__c</fullName>
    <label>Complemento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Centro_de_Distribuicao__c/fields/Endereco__c.field-meta.xml
<CustomField>
    <fullName>Endereco__c</fullName>
    <label>Endereço</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Centro_de_Distribuicao__c/fields/EnderecoReversa__c.field-meta.xml
<CustomField>
    <fullName>EnderecoReversa__c</fullName>
    <formula>LogradouroReversa__c &amp; &quot;, &quot; &amp; NumeroReversa__c &amp; &quot;, &quot; &amp; ComplementoReversa__c &amp; BR() &amp;
&quot;CEP: &quot; &amp; CepReversa__c &amp; &quot; - &quot; &amp; BairroReversa__c &amp; BR() &amp;
CidadeReversa__c &amp; &quot;/&quot; &amp; TEXT(UFReversa__c)</formula>
    <label>Endereço de Entrega Reversa</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Centro_de_Distribuicao__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do CD (SellerCode)</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Centro_de_Distribuicao__c/fields/LogradouroReversa__c.field-meta.xml
<CustomField>
    <fullName>LogradouroReversa__c</fullName>
    <description>Logradourao</description>
    <label>Logradouro</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Centro_de_Distribuicao__c/fields/NumeroReversa__c.field-meta.xml
<CustomField>
    <fullName>NumeroReversa__c</fullName>
    <label>Número</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Centro_de_Distribuicao__c/fields/UFReversa__c.field-meta.xml
<CustomField>
    <fullName>UFReversa__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/ObjetoPostagemReversa__c.object-meta.xml
<CustomObject>
    <description>Objeto criado para armazenar os objetos de Postagem Reversa criados para os casos de Postagem Reversa</description>
    <label>Objeto Postagem Reversa</label>
    <nameField>
        <displayFormat>OPS-{0000}</displayFormat>
        <label>Nome de Objeto Postagem Reversa</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objetos Postagem Reversa</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Objetos Postagem Reversa</relationshipLabel>
    <relationshipName>ObjetosPostagemReversa</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/idObjetoColeta__c.field-meta.xml
<CustomField>
    <fullName>idObjetoColeta__c</fullName>
    <label>idObjetoColeta__c</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/OrderItem__c.field-meta.xml
<CustomField>
    <fullName>OrderItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto do pedido</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Objetos Postagem Reversa</relationshipLabel>
    <relationshipName>Objetos_Postagem_Reversa</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Marca (Loja) da Pedido</description>
    <label>Marca</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>BrandOrder</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/CentrodeDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentrodeDistribuicao__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centro de Distribuição</label>
    <lookupFilter>
        <active>false</active>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Centro_de_Distribuicao__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>CDPedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Endereco__c.field-meta.xml
<CustomField>
    <fullName>Endereco__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Endereço</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/NumeroPedidoERP__c.field-meta.xml
<CustomField>
    <fullName>NumeroPedidoERP__c</fullName>
    <label>Número Pedido ERP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Chave Externa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup para o objeto Caso, para identificar qual produto foi trocado.</description>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Produtos do pedido</relationshipLabel>
    <relationshipName>OrderItemCase</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Sku__c.field-meta.xml
<CustomField>
    <fullName>Sku__c</fullName>
    <description>SKU ou EAN, Código de produto único.</description>
    <externalId>true</externalId>
    <label>SKU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Centro_de_Distribuicao__c.field-meta.xml
<CustomField>
    <fullName>Centro_de_Distribuicao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centro de Distribuição</label>
    <referenceTo>Centro_de_Distribuicao__c</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Produtos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SolicitarPostagemReversaLWCController.cls
public inherited sharing class SolicitarPostagemReversaLWCController {

    @AuraEnabled(Cacheable = true)
    public static List<OrderItemModel> getOrderItems(String caseId) {

        System.debug('caseId => ' + caseId);

        String orderId = [SELECT order__c FROM Case WHERE id =: caseId LIMIT 1].order__c;
        
        Map<Id, OrderItem> orderItems = new Map<Id, OrderItem>([SELECT id, product2.name, unitPrice, quantity, totalPrice, sku__c FROM OrderItem WHERE OrderId =: orderId]);

        List<OrderItemModel> result = new List<OrderItemModel>();

        Set<Id> orderItemsWithPostalObjectCreated = new Set<Id>();

        for(ObjetoPostagemReversa__c postalObject : [SELECT id, orderItem__c FROM ObjetoPostagemReversa__c WHERE orderItem__c IN :orderItems.keySet() AND caso__r.status != 'Closed']) {
            orderItemsWithPostalObjectCreated.add(postalObject.orderItem__c);
        }

        for(OrderItem orderItem : orderItems.values()) {
            if(!orderItemsWithPostalObjectCreated.contains(orderItem.id)) {
                result.add(new OrderItemModel(orderItem));
            }
        }

        System.debug('result => ' + JSON.serializePretty(result));

        return result;
    }

    @AuraEnabled
    public static Response createReversePost(String caseId, String orderItemIdsJSON){

        try {

            Type idArrType = Type.forName('List<string>');
            List<string> orderItemIds = (List<string>) JSON.deserialize(orderItemIdsJSON, idArrType);

            System.debug('caseId => ' + caseId);
            System.debug('orderItemIds => ' + orderItemIds);

            Case caseObj = [SELECT id, accountId, order__c, numeroColeta__c, ProtocolType__c FROM Case WHERE id = :caseId LIMIT 1];

            if(!String.isBlank(caseObj.numeroColeta__c)) {
                return new Response('Já existe uma coleta aberta para este caso.', true, null);
            }

            Account account = [
                SELECT id, phone, email__c, externalId__c, 
                (
                    SELECT  city__c, complement__c, country__c, neighborhood__c, 
                            number__c, postalCode__c, receiverName__c, street__c, 
                            state__c
                    FROM AccountAddress__r
                ) 
                FROM Account
                WHERE id = :caseObj.accountId
                LIMIT 1
            ];

            Order order = [
                SELECT id, numeroPedidoERP__c, brand__r.name, CentrodeDistribuicao__r.name, 
                endereco__r.city__c, endereco__r.complement__c, endereco__r.country__c, endereco__r.neighborhood__c, 
                endereco__r.number__c, endereco__r.postalCode__c, endereco__r.receiverName__c, endereco__r.street__c, endereco__r.state__c,
                centrodeDistribuicao__c, centrodeDistribuicao__r.bairroReversa__c, centrodeDistribuicao__r.cepReversa__c, 
                centrodeDistribuicao__r.cidadeReversa__c, centrodeDistribuicao__r.complementoReversa__c, centrodeDistribuicao__r.enderecoReversa__c, 
                centrodeDistribuicao__r.logradouroReversa__c, centrodeDistribuicao__r.numeroReversa__c, centrodeDistribuicao__r.ufReversa__c
                FROM Order
                WHERE id = :caseObj.order__c
            ];

            Centro_de_Distribuicao__c cdOrder = order.centrodeDistribuicao__r;

            Map<Id, OrderItem> orderItemMap = new Map<Id, OrderItem>([SELECT id, totalPrice FROM OrderItem WHERE id IN : orderItemIds]);

            Map<String, ObjetoPostagemReversa__c> idObjetoColetaToObjPostagemReversa = new Map<String, ObjetoPostagemReversa__c>();

            List<logisticaReversaCorreios.objeto> objList = new List<logisticaReversaCorreios.objeto>();

            Double totalItemsValue = 0;
            
            for(Integer i = 0; i < orderItemMap.keySet().size(); i++) {

                OrderItem currentOrderItem = orderItemMap.values().get(i);
                totalItemsValue += currentOrderItem.totalPrice;

                ObjetoPostagemReversa__c objPostagemReversa = new ObjetoPostagemReversa__c();
                objPostagemReversa.orderItem__c = currentOrderItem.id;
                
                String idObjetoColeta = String.valueOf(System.currentTimeMillis()) + i;
                objPostagemReversa.idObjetoColeta__c = idObjetoColeta;
                objPostagemReversa.caso__c = caseId;

                idObjetoColetaToObjPostagemReversa.put(idObjetoColeta, objPostagemReversa);

                logisticaReversaCorreios.objeto obj_col = new logisticaReversaCorreios.objeto();
                obj_col.item = '1';
                obj_col.id = idObjetoColeta;

                objList.add(obj_col);
            }

            System.debug('idObjetoColetaToObjPostagemReversa => ' + JSON.serializePretty(idObjetoColetaToObjPostagemReversa));

            logisticaReversaCorreios.pessoa destinatario = new logisticaReversaCorreios.pessoa();
            destinatario.nome = order.brand__r.name + '-' + order.CentrodeDistribuicao__r.name; // 'Joao'; // nome marca + nome cd
            
            // informações virão do centro de distribuição
            destinatario.logradouro = cdOrder.logradouroReversa__c;
            destinatario.numero = cdOrder.numeroReversa__c;
            destinatario.complemento = cdOrder.complementoReversa__c;
            destinatario.bairro = cdOrder.bairroReversa__c;
            destinatario.cidade = cdOrder.cidadeReversa__c;
            destinatario.uf = cdOrder.ufReversa__c;
            destinatario.cep = cdOrder.cepReversa__c.replaceAll('[^0-9]+', '');
            destinatario.ddd = '61';
            destinatario.telefone = '34261111';
            destinatario.email = 'joao';
            destinatario.ciencia_conteudo_proibido = 'N';
            
            // verificar de onde vem os dados de remetente
            logisticaReversaCorreios.remetente remetente = new logisticaReversaCorreios.remetente();
            Address__c receiverAddress = order.endereco__r;
            remetente.nome = receiverAddress.receiverName__c;
            remetente.logradouro = receiverAddress.street__c;
            remetente.numero = receiverAddress.number__c;
            remetente.complemento = receiverAddress.complement__c;
            remetente.bairro = receiverAddress.neighborhood__c;
            remetente.cidade = receiverAddress.city__c;
            remetente.uf = receiverAddress.state__c;
            remetente.cep = receiverAddress.postalCode__c.replaceAll('[^0-9]+', '');
            remetente.referencia = '';
            remetente.identificacao = account.externalId__c;
            String telefone = account.phone.replaceAll('\\+55', '');
            remetente.ddd_celular = telefone.substring(0, 2);
            remetente.celular = telefone.substring(2, telefone.length());
            remetente.sms = 'S';
            remetente.restricao_anac = 'S';
            
            String id_cliente = order.numeroPedidoERP__c; // String.valueOf(System.currentTimeMillis()); // numero pedido ERP (WEB-43891048)
            
            logisticaReversaCorreios.coletaReversa coletaReversa = new logisticaReversaCorreios.coletaReversa();

            System.debug('Antes: ' + String.valueOf(totalItemsValue));

            totalItemsValue = totalItemsValue > 21 ? totalItemsValue : 21.1;

            System.debug('Depois: ' + String.valueOf(totalItemsValue));

            coletaReversa.tipo = 'A';
            coletaReversa.id_cliente = id_cliente;
            coletaReversa.valor_declarado = String.valueOf(totalItemsValue); // String.valueOf(order.orderTotals__c);
            coletaReversa.remetente = remetente;
            coletaReversa.obj_col = objList;

            logisticaReversaCorreios.logisticaReversaWSPort l = new logisticaReversaCorreios.logisticaReversaWSPort();
            logisticaReversaCorreios.retornoPostagem retornoPostagem = l.solicitarPostagemReversa(destinatario, new List<logisticaReversaCorreios.coletaReversa>{coletaReversa});

            if(!String.isBlank(retornoPostagem.msg_erro) || retornoPostagem.cod_erro != '00') {
                String erro = String.isBlank(retornoPostagem.msg_erro)? retornoPostagem.resultado_solicitacao[0].descricao_erro : retornoPostagem.msg_erro;
                return new Response('Falha na Solicitação: ' + erro, true, null);
            }
            
            caseObj.idClientePostagemReversa__c = id_cliente;
            caseObj.numeroColeta__c = retornoPostagem.resultado_solicitacao[0].numero_coleta;
            caseObj.ReversaStatus__c = 'Aguardando Objeto na Agência';

            update caseObj;

            insert idObjetoColetaToObjPostagemReversa.values();

            if(caseObj.ProtocolType__c == 'return') {
                IntegrationCaseOUT.sendCaseOUTFuture(caseObj.Id);
            }

            return new Response('Sucesso! Registros de Objetos de Postagem Reversa gerados.', false, null);

        } catch (Exception e) {
            return new Response('Falha de Execução: ' + e.getMessage(), true, e.getStackTraceString());
        }
    }

    public class OrderItemModel {
        @AuraEnabled
        public String productName;
        @AuraEnabled
        public String price;
        @AuraEnabled
        public String sku;
        @AuraEnabled
        public String id;
        @AuraEnabled
        public String quantity;

        public OrderItemModel(OrderItem orderItem) {
            this.id          = orderItem.id;
            this.quantity    = String.valueOf(orderItem.quantity);
            this.productName = orderItem.product2.name;
            this.sku         = orderItem.sku__c;
            this.price       = String.valueOf(orderItem.unitPrice);
        }
    }
    
    public class Response {
        @AuraEnabled public String message;
        @AuraEnabled public Boolean isError;
        @AuraEnabled public String stackTrace;

        public Response(String message, Boolean isError, String stackTrace) {
            this.message     = message;
            this.isError     = isError;
            this.stackTrace  = stackTrace;
        }
    }
}