force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena as Marcas cadastradas no processo da Infracommerce.</description>
    <label>Marca</label>
    <nameField>
        <label>Nome da Marca</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marcas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand__c/fields/BusinessName__c.field-meta.xml
<CustomField>
    <fullName>BusinessName__c</fullName>
    <description>Nome Comercial da Marca que será usado nos templates de e-mails por exemplo.</description>
    <inlineHelpText>Insira o nome Comercial que será utilizado em templates de e-mail, contato com o consumidor e relatórios.</inlineHelpText>
    <label>Nome Comercial</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brand__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Brand__c/fields/SupportEmail__c.field-meta.xml
<CustomField>
    <fullName>SupportEmail__c</fullName>
    <description>E-mail utilizado para o suporte da Marca.</description>
    <inlineHelpText>Informar o E-mail do Suporte da Marca relacionada.</inlineHelpText>
    <label>E-mail do Suporte</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/ExternalCaseId__c.field-meta.xml
<CustomField>
    <fullName>ExternalCaseId__c</fullName>
    <externalId>true</externalId>
    <label>Número Externo de Caso</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Marca relacionada ao caso.</description>
    <label>Marca</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>MarcaCasos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Motivo do Caso</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Status do pagamento</fullName>
            </value>
            <value>
                <fullName>Status da entrega-CD</fullName>
            </value>
            <value>
                <fullName>Status da entrega-Transporte</fullName>
            </value>
            <value>
                <fullName>Cliente atesta não conformidade</fullName>
            </value>
            <value>
                <fullName>Cliente não gostou do produto</fullName>
            </value>
            <value>
                <fullName>Status reversa</fullName>
            </value>
            <value>
                <fullName>Conta</fullName>
            </value>
            <value>
                <fullName>Erro</fullName>
            </value>
            <value>
                <fullName>Produto</fullName>
            </value>
            <value>
                <fullName>Equipe</fullName>
            </value>
            <value>
                <fullName>Localização</fullName>
            </value>
            <value>
                <fullName>Promoções</fullName>
            </value>
            <value>
                <fullName>Parceria</fullName>
            </value>
            <value>
                <fullName>Dúvidas Loja Física</fullName>
            </value>
            <value>
                <fullName>Assistência Técnica</fullName>
            </value>
            <value>
                <fullName>Institucional Marca</fullName>
            </value>
            <value>
                <fullName>SAC Infra</fullName>
            </value>
            <value>
                <fullName>SAC Terceiro</fullName>
            </value>
            <value>
                <fullName>Atendimento Loja Física</fullName>
            </value>
            <value>
                <fullName>Atendimento Distribuidor</fullName>
            </value>
            <value>
                <fullName>Atendimento NRP</fullName>
            </value>
            <value>
                <fullName>Elogio do produto</fullName>
            </value>
            <value>
                <fullName>Elogio da marca</fullName>
            </value>
            <value>
                <fullName>Elogio atendimento</fullName>
            </value>
            <value>
                <fullName>Elogio do Site</fullName>
            </value>
            <value>
                <fullName>Elogio da Logística</fullName>
            </value>
            <value>
                <fullName>Elogio de Transporte</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Telefone</fullName>
            </value>
            <value>
                <fullName>Whatsapp</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ReversaStatus__c.field-meta.xml
<CustomField>
    <fullName>ReversaStatus__c</fullName>
    <description>Rastreia o processo de Reversa dos Correios através dos Status.</description>
    <label>Status da Reversa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando Objeto na Agência</fullName>
                <label>Aguardando Postagem Consumidor</label>
            </value>
            <value>
                <fullName>Prazo de Utilização Expirado</fullName>
                <label>Prazo de Postagem Expirado</label>
            </value>
            <value>
                <fullName>Coletado</fullName>
                <label>Em rota para o CD</label>
            </value>
            <value>
                <fullName>Entrega não realizada</fullName>
            </value>
            <value>
                <fullName>Aguardando Check-in Reversa</fullName>
            </value>
            <value>
                <fullName>Reversa Liberada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Encryption__c/Encryption__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Encryption</label>
</CustomObject>

force-app/main/default/objects/Encryption__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>AES chave utilizada na criptografia dos ids de registros utilizados na pesquisa de satisfação</description>
    <label>Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pesquisa_de_Satisfacao__c/Pesquisa_de_Satisfacao__c.object-meta.xml
<CustomObject>
    <label>Pesquisa de Satisfação</label>
    <nameField>
        <displayFormat>PS - {000000000}</displayFormat>
        <label>Nome de Pesquisa de Satisfação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pesquisas de Satisfação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pesquisa_de_Satisfacao__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Pesquisas de Satisfação</relationshipLabel>
    <relationshipName>Pesquisas_de_Satisfacao</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pesquisa_de_Satisfacao__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pesquisas de Satisfação</relationshipLabel>
    <relationshipName>Pesquisas_de_Satisfacao</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CaseTriggerHelperTest.cls
@IsTest
public with sharing class CaseTriggerHelperTest {

    private static final TestUtils testUtilsInstance = TestUtils.getInstance();
    

    @IsTest
    static void sendCorreiosExpiredTermEmail6() {
        Account acc = [SELECT id FROM Account LIMIT 1];
        Brand__c brand = [SELECT id FROM Brand__c LIMIT 1];
        Case caseObj = testUtilsInstance.createNewCase(null, acc);
        caseObj.marca__c = brand.id;
        insert caseObj;

        caseObj.ReversaStatus__c = 'Aguardando Check-in Reversa';
        update caseObj;

        Test.startTest();
            caseObj.ReversaStatus__c = 'Aguardando Check-in Reversa';
            update caseObj;
        Test.stopTest();

        // System.assert(!new List<Pesquisa_de_Satisfacao__c>([SELECT id FROM Pesquisa_de_Satisfacao__c WHERE conta__c = :acc.id AND caso__c = :caseObj.id]).isEmpty());
    }

    @IsTest
    static void sendCorreiosExpiredTermEmail5() {
        Account acc = [SELECT id FROM Account LIMIT 1];
        Brand__c brand = [SELECT id FROM Brand__c LIMIT 1];
        Case caseObj = testUtilsInstance.createNewCase(null, acc);
        
        caseObj.marca__c = brand.id;
        insert caseObj;

        caseObj.ReversaStatus__c = 'Entrega não realizada';
        update caseObj;


        Test.startTest();
            caseObj.ReversaStatus__c = 'Entrega não realizada';
            update caseObj;
        Test.stopTest();

        // System.assert(!new List<Pesquisa_de_Satisfacao__c>([SELECT id FROM Pesquisa_de_Satisfacao__c WHERE conta__c = :acc.id AND caso__c = :caseObj.id]).isEmpty());
    }
    
    @IsTest
    static void sendCorreiosExpiredTermEmail4() {
        Account acc = [SELECT id FROM Account LIMIT 1];
        Brand__c brand = [SELECT id FROM Brand__c LIMIT 1];
        Case caseObj = testUtilsInstance.createNewCase(null, acc);
        caseObj.marca__c = brand.id;
        insert caseObj;

        caseObj.ReversaStatus__c = 'Reversa Liberada';
        update caseObj;

        Test.startTest();
            caseObj.ReversaStatus__c = 'Reversa Liberada';
            update caseObj;
        Test.stopTest();

        // System.assert(!new List<Pesquisa_de_Satisfacao__c>([SELECT id FROM Pesquisa_de_Satisfacao__c WHERE conta__c = :acc.id AND caso__c = :caseObj.id]).isEmpty());
    }
    

    @IsTest
    static void sendCorreiosExpiredTermEmail3() {
        Account acc = [SELECT id FROM Account LIMIT 1];
        Brand__c brand = [SELECT id FROM Brand__c LIMIT 1];
        Case caseObj = testUtilsInstance.createNewCase(null, acc);
        caseObj.marca__c = brand.id;
        insert caseObj;

        caseObj.ReversaStatus__c = 'Coletado';
        update caseObj;

        Test.startTest();
            caseObj.ReversaStatus__c = 'Coletado';
            update caseObj;
        Test.stopTest();

        // System.assert(!new List<Pesquisa_de_Satisfacao__c>([SELECT id FROM Pesquisa_de_Satisfacao__c WHERE conta__c = :acc.id AND caso__c = :caseObj.id]).isEmpty());
    }

    
    @IsTest
    static void sendCorreiosExpiredTermEmail2() {
        Account acc = [SELECT id FROM Account LIMIT 1];
        Brand__c brand = [SELECT id FROM Brand__c LIMIT 1];
        Case caseObj = testUtilsInstance.createNewCase(null, acc);
        caseObj.marca__c = brand.id;
        insert caseObj;

    
        caseObj.ReversaStatus__c = 'Prazo de Utilização Expirado';
        update caseObj;

        Test.startTest();
            caseObj.ReversaStatus__c = 'Prazo de Utilização Expirado';
            update caseObj;
        Test.stopTest();

        // System.assert(!new List<Pesquisa_de_Satisfacao__c>([SELECT id FROM Pesquisa_de_Satisfacao__c WHERE conta__c = :acc.id AND caso__c = :caseObj.id]).isEmpty());
    }
    

    @IsTest
    static void sendCorreiosExpiredTermEmail() {
        Account acc = [SELECT id FROM Account LIMIT 1];
        Brand__c brand = [SELECT id FROM Brand__c LIMIT 1];
        Case caseObj = testUtilsInstance.createNewCase(null, acc);
        insert caseObj;

        Test.startTest();
            caseObj.ReversaStatus__c = 'Aguardando Objeto na Agência';
            update caseObj;
        Test.stopTest();

        // System.assert(!new List<Pesquisa_de_Satisfacao__c>([SELECT id FROM Pesquisa_de_Satisfacao__c WHERE conta__c = :acc.id AND caso__c = :caseObj.id]).isEmpty());
    }

    @IsTest
    static void fillProtocolType() {
        Account acc = [SELECT id FROM Account LIMIT 1];
        Brand__c brand = [SELECT id FROM Brand__c LIMIT 1];
        //First case
        Case caseObj = testUtilsInstance.createNewCase(null, acc);
        caseObj.Reason__c = 'Cliente atesta não conformidade';
        caseObj.Type = 'Atendimento sobre a Troca';
        insert caseObj;

        //Second case
        Case caseObj2 = testUtilsInstance.createNewCase(null, acc);
        caseObj2.Reason__c = 'Cliente não gostou do produto';
        caseObj2.Type = 'Atendimento sobre a Devolução';
        insert caseObj2;


        Test.startTest();
            update caseObj;
            update caseObj2;
        Test.stopTest();

        // System.assert(!new List<Pesquisa_de_Satisfacao__c>([SELECT id FROM Pesquisa_de_Satisfacao__c WHERE conta__c = :acc.id AND caso__c = :caseObj.id]).isEmpty());
    }

    public static EmailTemplate getPesquisaSatisfacaoEmailTestTemplate(){
        return new EmailTemplate(
            DeveloperName = 'PesquisaSatisfacao', 
            TemplateType = 'html', 
            FolderId = UserInfo.getUserId(),
            Body = '{!NomeConta} {!NumeroCaso} {!link}',
            HtmlValue = '{!NomeConta} {!NumeroCaso} {!link}',
            Name = 'Pesquisa Satisfação'
        ); 
    }

    @TestSetup
    static void makeData(){
        CaseTriggerHandler.enableTrigger();
        CaseTriggerHandler.disableTrigger();

        Blob key = Crypto.generateAesKey(128);

        Encryption__c encryption = new Encryption__c(
            key__c = EncodingUtil.base64Encode(key)
        );
        insert encryption;

        Account account = testUtilsInstance.createNewAccount(null);
        insert account;

        Brand__c brand = new Brand__c(name = 'Armani', externalId__c = 'Armani', businessName__c = 'Armani', SupportEmail__c = 'armaniatendimento@sac.com.br');
        insert brand;
    }

    @IsTest
    static void sendSurveyEmailTest() {
        Account acc = [SELECT id FROM Account LIMIT 1];
        Brand__c brand = [SELECT id FROM Brand__c LIMIT 1];
        Case caseObj = testUtilsInstance.createNewCase(null, acc);
        caseObj.marca__c = brand.id;
        insert caseObj;

        Test.startTest();
            caseObj.status = 'Closed';
            update caseObj;
        Test.stopTest();

        // System.assert(!new List<Pesquisa_de_Satisfacao__c>([SELECT id FROM Pesquisa_de_Satisfacao__c WHERE conta__c = :acc.id AND caso__c = :caseObj.id]).isEmpty());
    }

    @IsTest
    //testing Pesquisa_de_Satisfacao__c record creation limit
    static void sendSurveyEmailTest2() {
        Account acc = [SELECT id FROM Account LIMIT 1];
        Brand__c brand = [SELECT id FROM Brand__c LIMIT 1];
        Case caseObj = testUtilsInstance.createNewCase(null, acc);
        caseObj.marca__c = brand.id;
        insert caseObj;

        caseObj.status = 'Closed';
        update caseObj;

        // System.assert(!new List<Pesquisa_de_Satisfacao__c>([SELECT id FROM Pesquisa_de_Satisfacao__c WHERE conta__c = :acc.id AND caso__c = :caseObj.id]).isEmpty());

        caseObj.status = 'Em atendimento';
        update caseObj;

        Test.startTest();
            caseObj.status = 'Closed';
            update caseObj;
        Test.stopTest();

        // System.assert([SELECT id FROM Pesquisa_de_Satisfacao__c WHERE conta__c = :acc.id AND caso__c = :caseObj.id].size() == 1);
    }

    @IsTest
    static void createTaskToIntegrationRuptureCaseTest() {
        Account acc = [SELECT id FROM Account LIMIT 1];
        System.debug('acc ' + acc);
        Brand__c brand = [SELECT id FROM Brand__c LIMIT 1];
        System.debug('brand ' + brand);

        // Case caseObj = testUtilsInstance.createNewCase(null, acc);
        // caseObj.Reason__c = 'Cliente atesta não conformidade';
        // caseObj.Type = 'Atendimento sobre a Troca';
        // caseObj.Subject  = 'Ruptura de Pedido';
        // caseObj.ExternalCaseId__c  = 'IHUB2-2121633199';
        
        // insert caseObj;

        Case caseObj = testUtilsInstance.createNewCase(null, acc);
        // caseObj.Type = 'Atendimento sobre o Pedido';
        caseObj.Subject  = 'Ruptura';
        caseObj.ExternalCaseId__c  = 'IHUB2-2121633199';

        System.debug('caseObj pré' + caseObj);
        insert caseObj;
        System.debug('caseObj pós' + caseObj);


    }
}