force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena os múltiplos endereços da conta.</description>
    <label>Endereço</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Endereço</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Endereços</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Relacionamento com o objeto Conta.</description>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Endereços</relationshipLabel>
    <relationshipName>AccountAddress</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Campo com o Endereço completo de Cobrança.</description>
    <formula>ReceiverName__c &amp; BR() &amp; 
Street__c &amp; &quot;, &quot; &amp; Number__c &amp; BR() &amp; 
Neighborhood__c &amp; &quot; - &quot; &amp; &quot;CEP: &quot; &amp; PostalCode__c &amp; BR() &amp;
City__c  &amp; &quot;/&quot; &amp; TEXT(State__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Endereço Completo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/AddressType__c.field-meta.xml
<CustomField>
    <fullName>AddressType__c</fullName>
    <label>Tipo de endereço</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
                <default>true</default>
                <label>Casa</label>
            </value>
            <value>
                <fullName>Commercial</fullName>
                <label>Comercial</label>
            </value>
            <value>
                <fullName>Apartment</fullName>
                <label>Apartamento</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <label>Outro</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Campo Cidade do Endereço de Cobrança.</description>
    <label>Cidade</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Complement__c.field-meta.xml
<CustomField>
    <fullName>Complement__c</fullName>
    <description>Complemento do Endereço.</description>
    <label>Complemento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>País do Endereço de Cobrança.</description>
    <label>País</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Chave Externa</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Address__c/fields/Neighborhood__c.field-meta.xml
<CustomField>
    <fullName>Neighborhood__c</fullName>
    <description>Bairro do Endereço</description>
    <label>Bairro</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <description>Número do endereço.</description>
    <label>Número</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <description>Campo de CEP do Endereço (Postal Code)</description>
    <label>CEP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/ReceiverName__c.field-meta.xml
<CustomField>
    <fullName>ReceiverName__c</fullName>
    <description>Nome do destinatário.</description>
    <label>Nome do destinatário</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Campo de Estado do Endereço de Cobrança.</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Campo Rua do Endereço de Cobrança.</description>
    <label>Rua</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazena as Marcas cadastradas no processo da Infracommerce.</description>
    <label>Marca</label>
    <nameField>
        <label>Nome da Marca</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marcas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Marca relacionada ao caso.</description>
    <label>Marca</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>MarcaCasos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Relacionamento com o Pedido do Cliente.</description>
    <label>Pedido</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Order.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Casos (Pedido)</relationshipLabel>
    <relationshipName>OrderCase</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Centro_de_Distribuicao__c/Centro_de_Distribuicao__c.object-meta.xml
<CustomObject>
    <label>Centro de Distribuição</label>
    <nameField>
        <label>Nome de Centro de Distribuição</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centros de Distribuição</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Centro_de_Distribuicao__c/fields/BairroReversa__c.field-meta.xml
<CustomField>
    <fullName>BairroReversa__c</fullName>
    <label>Bairro</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Centro_de_Distribuicao__c/fields/CepReversa__c.field-meta.xml
<CustomField>
    <fullName>CepReversa__c</fullName>
    <label>CEP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Centro_de_Distribuicao__c/fields/Endereco__c.field-meta.xml
<CustomField>
    <fullName>Endereco__c</fullName>
    <label>Endereço</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Centro_de_Distribuicao__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do CD (SellerCode)</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Marca (Loja) da Pedido</description>
    <label>Marca</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>BrandOrder</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/CentrodeDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentrodeDistribuicao__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centro de Distribuição</label>
    <lookupFilter>
        <active>false</active>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Centro_de_Distribuicao__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>CDPedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Endereco__c.field-meta.xml
<CustomField>
    <fullName>Endereco__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Endereço</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Chave Externa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup para o objeto Caso, para identificar qual produto foi trocado.</description>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Produtos do pedido</relationshipLabel>
    <relationshipName>OrderItemCase</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Centro_de_Distribuicao__c.field-meta.xml
<CustomField>
    <fullName>Centro_de_Distribuicao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centro de Distribuição</label>
    <referenceTo>Centro_de_Distribuicao__c</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Produtos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marca</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SolicitarPostagemReversaLWCTest.cls
@IsTest
public class SolicitarPostagemReversaLWCTest {
    
    private static final TestUtils testUtilsInstance = TestUtils.getInstance();

    @TestSetup
    static void makeData() {
        Account acc = new Account(Name = 'Test Account');
        acc = testUtilsInstance.createNewAccount(acc);
        insert acc;

        Product2 product1 = new Product2(
            Name = 'Test Product 1',
            Description = 'First Test Product',
            ProductCode = 'ABC',
            IsActive = true,
            ExternalId__c = 'TestProduct1'
        );

        Product2 product2 = new Product2(
            Name = 'Test Product 2',
            Description = 'Second Test Product',
            ProductCode = 'DEF',
            IsActive = true,
            ExternalId__c = 'TestProduct2'
        );
        insert new List<Product2>{product1, product2};

        Id pricebookId = Test.getStandardPricebookId();

        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = product1.Id,
            UnitPrice = 10,
            IsActive = true,
            UseStandardPrice = false,
            ExternalID__c = 'PricebookEntry1'
        );

        PricebookEntry standardPrice2 = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = product2.Id,
            UnitPrice = 20,
            IsActive = true,
            UseStandardPrice = false,
            ExternalID__c = 'PricebookEntry2'
        );

        insert new List<PricebookEntry>{standardPrice, standardPrice2};

        Brand__c brand = new Brand__c(
            ExternalID__c = 'BrandA'
        );
        insert brand;

        Address__c address = new Address__c(
            Account__c = acc.Id, 
            AddressType__c = 'Residential',
            City__c = 'Porto Alegre',
            Complement__c = 'Aparento 409b',
            Country__c = 'BRA',
            Neighborhood__c = 'Glória',
            Number__c = '1123',
            PostalCode__c = '90680-570',
            ReceiverName__c = 'Paulo Floss',
            State__c = 'RS',
            Street__c = 'Rua Coronel Aparício Borges'
        );
        insert address;

        Centro_de_Distribuicao__c cd = new Centro_de_Distribuicao__c(
            ExternalID__c = 'cd',
            BairroReversa__c = 'Bairro Reversa',
            CepReversa__c = '09450-000'/*,
            Marca__c = brand.Id*/
        );
        // insert cd;
        
        Order order = new Order(
            AccountId = acc.Id,
            Name = 'Test Order',
            Status = 'Draft',
            EffectiveDate = System.today(),
            EndDate = System.today() + 4,
            Pricebook2Id = pricebookId,
            Endereco__c = address.Id
            // CentrodeDistribuicao__c = cd.Id
        );
        insert order;

        OrderItem orderItem1 = new OrderItem(
            OrderId = order.Id,
            Quantity = 2,
            UnitPrice = 120,
            Product2Id = product1.Id, 
            PricebookEntryId = standardPrice.Id
        );

        OrderItem orderItem2 = new OrderItem(
            OrderId = order.Id,
            Quantity = 2,
            UnitPrice = 160,
            Product2Id = product2.Id, 
            PricebookEntryId = standardPrice2.Id
        );

        insert new List<OrderItem>{orderItem1, orderItem2};

        Case caseObj = new Case(AccountId = acc.id, Order__c = order.Id);
        insert caseObj;
    }
    
    static testMethod void getOrderItemsTest() {
        Case caseObj = [SELECT id FROM Case LIMIT 1];
        List<SolicitarPostagemReversaLWCController.OrderItemModel> orderItemModels = SolicitarPostagemReversaLWCController.getOrderItems(caseObj.Id);
    }

    static testMethod void createReversePostTest() {
        Case caseObj = [SELECT id FROM Case LIMIT 1];
        Map<Id, OrderItem> orderItemsMap = new Map<Id, OrderItem>([SELECT id FROM OrderItem]);
        
        SolicitarPostagemReversaLWCController.Response response = SolicitarPostagemReversaLWCController.createReversePost(caseObj.Id, JSON.serialize(orderItemsMap.keySet()));
    }
}