force-app/main/default/objects/ObjetoPostagemReversa__c/ObjetoPostagemReversa__c.object-meta.xml
<CustomObject>
    <description>Objeto criado para armazenar os objetos de Postagem Reversa criados para os casos de Postagem Reversa</description>
    <label>Objeto Postagem Reversa</label>
    <nameField>
        <displayFormat>OPS-{0000}</displayFormat>
        <label>Nome de Objeto Postagem Reversa</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objetos Postagem Reversa</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Objetos Postagem Reversa</relationshipLabel>
    <relationshipName>ObjetosPostagemReversa</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/DataUltimaAtualizacao__c.field-meta.xml
<CustomField>
    <fullName>DataUltimaAtualizacao__c</fullName>
    <label>Data da Última Atualização</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/HoraUltimaAtualizacao__c.field-meta.xml
<CustomField>
    <fullName>HoraUltimaAtualizacao__c</fullName>
    <label>Hora da Última Atualização</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/idObjetoColeta__c.field-meta.xml
<CustomField>
    <fullName>idObjetoColeta__c</fullName>
    <label>idObjetoColeta__c</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/NumeroEtiqueta__c.field-meta.xml
<CustomField>
    <fullName>NumeroEtiqueta__c</fullName>
    <label>Número de Rastreamento</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ObjetoPostagemReversa__c/fields/UltimoStatusRastreamento__c.field-meta.xml
<CustomField>
    <fullName>UltimoStatusRastreamento__c</fullName>
    <label>Último Status de Rastreamento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PosPostagemController.cls
public with sharing class PosPostagemController {

    @AuraEnabled 
    public static String PosPostagemController(String recordId) {

        try {

            Case caso = [
                SELECT  id, 
                    (   SELECT id, idObjetoColeta__c, NumeroEtiqueta__c, UltimoStatusRastreamento__c
                        FROM ObjetosPostagemReversa__r
                    )
                FROM    Case 
                WHERE   id =: recordId
            ];

            if(caso.ObjetosPostagemReversa__r.isEmpty()) {
                return 'Não há nenhum objeto de postagem reversa criado para este case. Solicite a Postagem Reversa dos Itens.';
            }

            Map<String, ObjetoPostagemReversa__c> numeroEtiquetaToObjetoPostagemReversa = new Map<String, ObjetoPostagemReversa__c>();

            for(ObjetoPostagemReversa__c objPostagemReversa : caso.ObjetosPostagemReversa__r) {
                if(!String.isBlank(objPostagemReversa.NumeroEtiqueta__c)) {
                    numeroEtiquetaToObjetoPostagemReversa.put(objPostagemReversa.NumeroEtiqueta__c, objPostagemReversa);
                }
            }

            if(numeroEtiquetaToObjetoPostagemReversa.keySet().isEmpty()) {
                return 'Não há nenhum objeto de postagem reversa com o número etiqueta. Solicite o Número de Etiqueta (E-Ticket) dos Itens.';
            }
            
            SroXML2 response = RastreioCallout.getStatusRastreamento(new List<String>(numeroEtiquetaToObjetoPostagemReversa.keySet()));

            for(SROXML2.ObjetoRastreio objeto : response.objeto) {
                System.debug('objeto => ' + JSON.serializePretty(objeto));
                System.debug('objeto.numero => ' + objeto.numero);
                System.debug('objeto.descricao => ' + objeto.evento[0].descricao);
                numeroEtiquetaToObjetoPostagemReversa.get(objeto.numero).UltimoStatusRastreamento__c = objeto.evento[0].descricao;
                numeroEtiquetaToObjetoPostagemReversa.get(objeto.numero).DataUltimaAtualizacao__c    = objeto.evento[0].data;
                numeroEtiquetaToObjetoPostagemReversa.get(objeto.numero).HoraUltimaAtualizacao__c    = objeto.evento[0].hora;
            }

            update numeroEtiquetaToObjetoPostagemReversa.values();

            return 'Sucesso! Últimos status dos objetos com número etiqueta atualizados.';

        } catch (Exception e) {
            return 'Erro: ' + e.getMessage();
        }
    }
}